-- SpokenZones -- the language axis.
--
-- Two identifiers live here and are deliberately never merged:
--
--   client locale   GetLocale(). Decides what GetSubZoneText and
--                   MapUtil.FindBestAreaNameAtMouse hand back, and therefore
--                   which alias table turns those names into corpus keys. Also
--                   decides which glyphs the client's fonts can draw -- and,
--                   for that same reason, which interface strings load: a client
--                   only ever loads its own locale's file, so its UI is always
--                   renderable.
--
--   content language  What the player chose to read and hear. Decides which
--                   lore table is primary and which sound pack plays. Deliberately
--                   NOT which UI strings are used: those follow the client, so a
--                   translation shows the moment it exists instead of waiting for
--                   the whole lore corpus to be finished.
--
-- A German client reading English lore still needs German aliases. Getting that
-- backwards is the failure that presents as "the addon just does not work in
-- German", so every function below says which of the two it takes.
--
-- This file loads before Core.lua and before anything under Data/, because the
-- generated data files ask ShouldLoadLanguage whether to build their tables at
-- all. That question can only be answered this early because SpokenZones.toc sets
-- LoadSavedVariablesFirst -- SpokenZonesDB is already populated when these files
-- run. Removing that .toc line does not error; it silently pins every player to
-- English.

local ADDON_NAME, SpokenZones = ...

-- Every locale a Classic Era or Anniversary client can run in. A code absent
-- here can never be selected, so the list is the addon's definition of "a
-- language", not a list of languages that have content -- readiness is a
-- separate question, answered by Data/Languages.lua.
--
-- `script` is what the client's fonts must be able to draw. `name` is ASCII so
-- it survives being printed on a client whose fonts cannot draw `native`.
-- `native` is the endonym shown wherever a language is listed -- Latin-script
-- endonyms draw on every client, and anything else is only ever listed where
-- CanRenderLanguage already passed, so no list can show boxes.
--
-- Must stay in step with LOCALES in tools/lib/locales.mjs; tools/validate.mjs
-- fails the build if the two lists drift.
SpokenZones.LOCALES = {
	{ code = "enUS", name = "English", native = "English", script = "latin" },
	{ code = "deDE", name = "German", native = "Deutsch", script = "latin" },
	{ code = "esES", name = "Spanish (EU)", native = "Español (España)", script = "latin" },
	{ code = "esMX", name = "Spanish (AL)", native = "Español (América Latina)", script = "latin" },
	{ code = "frFR", name = "French", native = "Français", script = "latin" },
	{ code = "ptBR", name = "Portuguese", native = "Português", script = "latin" },
	{ code = "ruRU", name = "Russian", native = "Русский", script = "cyrillic" },
	{ code = "koKR", name = "Korean", native = "한국어", script = "korean" },
	{ code = "zhCN", name = "Chinese (S)", native = "简体中文", script = "simplifiedchinese" },
	{ code = "zhTW", name = "Chinese (T)", native = "繁體中文", script = "traditionalchinese" },
}

local BASE = "enUS"

local byCode = {}
for i = 1, #SpokenZones.LOCALES do
	byCode[SpokenZones.LOCALES[i].code] = SpokenZones.LOCALES[i]
end

SpokenZones.clientLocale = GetLocale()

-- Localized area name -> English corpus key, keyed by *client* locale.
-- Populated by Data/<locale>/Aliases.lua.
SpokenZones.Aliases = {}

--------------------------------------------------------------------------------
-- Readiness
--------------------------------------------------------------------------------

-- Coverage per language, generated by tools/locale/build-languages.mjs into
-- Data/Languages.lua. Declared here so this file works before that one loads and
-- on a build where it is missing: without it only English exists, which is the
-- state the addon shipped in for its whole life so far.
SpokenZones.Languages = SpokenZones.Languages or {}

local function coverage(code)
	local list = SpokenZones.Languages
	for i = 1, #list do
		if list[i].code == code then
			return list[i]
		end
	end
	return nil
end

-- A language is ready when every lore line has a translation (and, for a
-- non-English one, an alias table). Interface strings are not required -- they
-- fall back to English per key. Computed at build time rather than counted
-- here, because the addon cannot know how many lines there are supposed to be.
function SpokenZones:IsLanguageReady(code)
	if code == BASE then
		return true
	end
	local entry = coverage(code)
	return (entry and entry.ready) and true or false
end

-- Whether this client's fonts can draw this language. The lore panel takes its
-- font from GameFontHighlight (see UI/TextView.lua), which is the *client's*
-- font, so Chinese lore on a German client is a screen of boxes -- a bug report
-- that looks like corrupted data. English is always allowed: it is what the addon
-- falls back to when nothing else can be selected, and every client can draw it.
function SpokenZones:CanRenderLanguage(code)
	if code == BASE then
		return true
	end
	local locale = byCode[code]
	if not locale then
		return false
	end
	if locale.script == "latin" then
		return true
	end
	local client = byCode[self.clientLocale]
	return client ~= nil and client.script == locale.script
end

--------------------------------------------------------------------------------
-- Selection
--------------------------------------------------------------------------------

-- The stored preference for this client, or nil for "follow the client". The
-- two are not the same: a player who never chose should start reading German
-- the day German ships, while one who explicitly picked English must keep
-- English -- on that client. SavedVariables are shared across clients, so the
-- preference is keyed by client locale: a single global would pin a French
-- client to the Spanish somebody picked on the Spanish one. Each client
-- remembers its own choice and follows itself by default.
function SpokenZones:GetLanguagePreference()
	local db = SpokenZonesDB
	if not db then
		return nil
	end
	local perClient = db.languageByLocale
	local pref = type(perClient) == "table" and perClient[self.clientLocale] or nil
	if pref == nil then
		-- Single preference from before choices were per client. Honored only
		-- where it already matches this client: a stored Spanish belongs to
		-- the Spanish client, and a French client must not inherit it.
		if db.language == self.clientLocale then
			pref = db.language
		end
	end
	return type(pref) == "string" and byCode[pref] and pref or nil
end

function SpokenZones:IsPreviewingLanguage()
	return (SpokenZonesDB and SpokenZonesDB.languagePreview) and true or false
end

-- Whether a language may be selected at all. Preview mode relaxes readiness so
-- an unfinished translation can be looked at, but never relaxes the font check:
-- previewing boxes tells you nothing.
function SpokenZones:IsLanguageSelectable(code)
	if not byCode[code] then
		return false
	end
	if not self:CanRenderLanguage(code) then
		return false
	end
	return self:IsLanguageReady(code) or self:IsPreviewingLanguage()
end

local function resolve()
	local pref = SpokenZones:GetLanguagePreference()
	if pref and SpokenZones:IsLanguageSelectable(pref) then
		return pref
	end
	local client = SpokenZones.clientLocale
	if byCode[client] and SpokenZones:IsLanguageReady(client) and SpokenZones:CanRenderLanguage(client) then
		return client
	end
	return BASE
end

-- Resolved once, at load, and never recomputed: the generated data files consult
-- it as they load and only get one chance to build their table. Everything that
-- changes the answer therefore asks for a /reload.
SpokenZones.language = resolve()

function SpokenZones:GetLanguage()
	return self.language
end

-- Every language the player could pick right now, in LOCALES order.
function SpokenZones:GetSelectableLanguages()
	local out = {}
	for i = 1, #self.LOCALES do
		local locale = self.LOCALES[i]
		if self:IsLanguageSelectable(locale.code) then
			table.insert(out, locale)
		end
	end
	return out
end

function SpokenZones:GetLocaleInfo(code)
	return byCode[code]
end

-- Display name of a language: its own endonym. Only call it where the name is
-- drawable -- the dropdown, the language list and the pack label all list
-- renderable languages only. Anywhere else (the no-fonts warning) uses the code,
-- which is ASCII on every client.
function SpokenZones:GetLanguageName(code)
	local locale = byCode[code or BASE]
	if not locale then
		return tostring(code)
	end
	return locale.native or locale.name
end

-- Stores the preference for this client. Returns false when the language is not
-- selectable, so the caller can say why rather than storing a choice that
-- resolves to English.
--
-- Takes effect on /reload. Nothing here fakes a live switch: the tables for a
-- language that was not active at load were never built, and pretending
-- otherwise would show half-translated screens.
function SpokenZones:SetLanguage(code)
	if code ~= nil and not self:IsLanguageSelectable(code) then
		return false
	end
	SpokenZonesDB.languageByLocale = SpokenZonesDB.languageByLocale or {}
	SpokenZonesDB.languageByLocale[self.clientLocale] = code
	SpokenZonesDB.language = nil
	return true
end

function SpokenZones:SetLanguagePreview(enabled)
	SpokenZonesDB.languagePreview = enabled and true or false
end

--------------------------------------------------------------------------------
-- Interface strings
--
-- SpokenZones.L is every string the interface can show, looked up by name:
-- the active language first, English second, and the key itself last so a
-- missing string is legible on screen rather than a nil concatenation error.
--
-- SCAFFOLDING. Only a few files draw their text from here so far -- see
-- Locale/enUS.lua for which -- and the rest still hold English literals. The
-- pattern to follow when converting one is in UI/SoundQueueUI.lua, and the rule
-- that matters is positional format arguments (%1$s), because word order is
-- exactly what a translator cannot fix inside a Lua concatenation.
--------------------------------------------------------------------------------

SpokenZones.Strings = { enUS = {} }

local warnedMissing = {}

SpokenZones.L = setmetatable({}, {
	__index = function(_, key)
		-- Interface strings follow the client, not the content language: the
		-- locale file for any other code never loads on this client, so there
		-- is nothing else it could fall back to before English.
		local active = SpokenZones.Strings[SpokenZones.clientLocale]
		local value = active and active[key]
		if value ~= nil then
			return value
		end

		value = SpokenZones.Strings.enUS[key]
		if value ~= nil then
			return value
		end

		-- Only in debug mode, and only once: a key with no English string is a
		-- bug in this addon rather than a gap in a translation, and it should be
		-- findable by playing rather than by grepping.
		if SpokenZones:Get("debug") and not warnedMissing[key] then
			warnedMissing[key] = true
			SpokenZones:Print("|cffffcc00no string for|r [[%s]]", key)
		end
		return "[[" .. key .. "]]"
	end,
})

-- Called by Locale/<code>.lua, which guards itself on the client locale in
-- the same way every WoW addon does: interface strings are useful the moment
-- one of them exists, unlike lore, which is only offered whole.
--
-- STRINGS DO FALL BACK TO ENGLISH, unlike the lore. A missing string is an unlabelled
-- button, and an English label is a strictly better answer than an empty one; a
-- missing line of lore has an honest empty state, which prose from another language
-- does not improve on. The readiness gate demands 100% of both before a language is
-- offered, so both paths are safety nets rather than plans.
function SpokenZones:RegisterStrings(code, strings)
	self.Strings[code] = strings
end

--------------------------------------------------------------------------------
-- Registration
--
-- The generated data files hand their tables here rather than assigning the
-- globals directly. That indirection is the escape hatch: if parsing every
-- language at login becomes measurable, each Data/<code>/ moves into its own
-- LoadOnDemand addon inside the same zip and calls exactly these functions.
--------------------------------------------------------------------------------

-- Whether a generated data file for `code` should build its table.
--
-- ONLY THE ACTIVE LANGUAGE. There is no English fallback per line: a place with no
-- lore in the language being read shows nothing, exactly as a zone with no lore at
-- all does. Falling back would put English prose under a German heading, which
-- reads as a translation somebody did badly rather than one nobody has done -- and
-- the readiness gate means a language on offer has no holes to fall through
-- anyway. See SpokenZones.Languages and the /spz lang preview override.
function SpokenZones:ShouldLoadLanguage(code)
	return code == self.language
end

function SpokenZones:RegisterLoreData(code, kind, data)
	if code ~= self.language then
		return
	end
	self[(kind == "zones") and "Zones" or "Subzones"] = data
end

-- Aliases are keyed by client locale, not content language, so this guard is
-- deliberately not ShouldLoadLanguage.
function SpokenZones:ShouldLoadAliases(locale)
	return locale == self.clientLocale
end

function SpokenZones:RegisterAliases(locale, data)
	self.Aliases[locale] = data
end
