-- Generated by `make quests-export-gossip-text`; do not edit.
--
-- The other files a gossip line's moment is recorded under: same BroadcastText id, same
-- voice. Tried after the line's own file. See pipelines/quests/tts_cli/gossip_text.py.
setfenv(1, VoiceOver)

GossipAliases = {
    ["0cc088f013cb6fc40acf3a7acfed831d"] = { "e841ba6ae28aa6b32a74b9d08e9fed88" },
    ["292d23a69067576b9fc2d7040777f5f2"] = { "f9930fe3fe43966e931eb3d5ec87d2be" },
    ["58a07ba5d668196689ecb253dea303f8"] = { "ddd4d55dd1de943c233b8a47f730d0f9" },
    ["650cd75a030b0fef3f59f216d895e8d1"] = { "ca5ae8d63433bb1a991ae3a7d4a633fc" },
    ["6ac10856479660152ac493ee64b58f4e"] = { "d60817dbe236b7089fc232eee4ef8e4a" },
    ["78c72b92c02d69f67b68bb8842819441"] = { "b2544c3bf97ec106583835dc5a2aaaf1" },
    ["9331c7d44a0e3e3352a08f93cde78162"] = { "d9ee732b87b8a6f2898035304c1bf290" },
    ["b2544c3bf97ec106583835dc5a2aaaf1"] = { "78c72b92c02d69f67b68bb8842819441" },
    ["ca5ae8d63433bb1a991ae3a7d4a633fc"] = { "650cd75a030b0fef3f59f216d895e8d1" },
    ["d60817dbe236b7089fc232eee4ef8e4a"] = { "6ac10856479660152ac493ee64b58f4e" },
    ["d9ee732b87b8a6f2898035304c1bf290"] = { "9331c7d44a0e3e3352a08f93cde78162" },
    ["ddd4d55dd1de943c233b8a47f730d0f9"] = { "58a07ba5d668196689ecb253dea303f8" },
    ["e841ba6ae28aa6b32a74b9d08e9fed88"] = { "0cc088f013cb6fc40acf3a7acfed831d" },
    ["f9930fe3fe43966e931eb3d5ec87d2be"] = { "292d23a69067576b9fc2d7040777f5f2" },
}
