-- AUTO-GENERATED by tools/lore/export-forever-areas.mjs. Do not edit by hand.
--
-- The areas only the Forever client has: in its AreaTable and not in Era's (build 1.15.9.69109).
-- Lore of Azeroth leaves them out on any other client, which can never report them. Keyed as
-- Subzones.lua is: uiMapID, then the normalised area name.

local _, SpokenZones = ...

SpokenZones.ForeverOnlyAreas = {
	[1412] = {
		["camp gevrek"] = true,
		["galak camp"] = true,
		["gloomrise"] = true,
		["skywatcher plateau"] = true,
	},
	[1416] = {
		["eventide"] = true,
		["old dalaran ruins"] = true,
	},
	[1420] = {
		["bandarion keep"] = true,
		["shadowvale"] = true,
		["whispering forest"] = true,
	},
	[1425] = {
		["martsirt"] = true,
	},
	[1426] = {
		["ironforge submarine facility"] = true,
	},
	[1428] = {
		["poachers den"] = true,
	},
	[1429] = {
		["northshire valley camelot"] = true,
	},
	[1437] = {
		["dragonmaw retreat"] = true,
		["drunken dwarf"] = true,
		["excavation site wetlands"] = true,
	},
	[1441] = {
		["scalding ridge"] = true,
	},
	[1447] = {
		["blackmaw hold"] = true,
		["legashi encampment"] = true,
		["legashi stronghold"] = true,
		["thalassian vanguard camp"] = true,
	},
	[1449] = {
		["pillar of assimilation"] = true,
		["shapers terrace"] = true,
		["stomping grounds"] = true,
	},
	[1453] = {
		["stormwind harbor"] = true,
	},
	[2482] = {
		["cradle of tranquility"] = true,
		["daegun"] = true,
		["elderwild"] = true,
		["felblood scar"] = true,
		["malornes retreat"] = true,
		["mournings rest"] = true,
		["shrine of aviana"] = true,
		["summit of eternity"] = true,
		["tainted foothills"] = true,
	},
	[2521] = {
		["bandit hideout"] = true,
		["east pylon watchtower"] = true,
		["fairweather stables"] = true,
		["falaath village"] = true,
		["gustberry lowlands"] = true,
		["nightclaw cavern"] = true,
		["overlook standing stones"] = true,
		["rise of spirits"] = true,
		["rohashi spires"] = true,
		["ruins of banaethal"] = true,
		["sanctum of storms"] = true,
		["shadowgale forest"] = true,
		["shendar highlands"] = true,
		["shendar village"] = true,
		["shriekling den"] = true,
		["shrine of akir"] = true,
		["skywall"] = true,
		["thendal cave"] = true,
		["thendal grove"] = true,
		["thendal standing stones"] = true,
		["thendal village"] = true,
		["valanaar"] = true,
		["valanaar skydocks"] = true,
		["west pylon watchtower"] = true,
		["windfield orchard"] = true,
		["windsong lake"] = true,
		["windsong standing stones"] = true,
	},
	[2524] = {
		["abandoned tower"] = true,
		["shipwreck cove"] = true,
	},
	[2548] = {
		["ashwoods fall"] = true,
		["bolderok"] = true,
		["bristle hills"] = true,
		["eastwind shore"] = true,
		["elbrims farm"] = true,
		["farholde keep"] = true,
		["forlorn pit"] = true,
		["kroldok stronghold"] = true,
		["meadowsbrook"] = true,
		["powderfuse port"] = true,
		["rogmar"] = true,
		["southern watch"] = true,
		["sunnyglade"] = true,
		["terrals watch"] = true,
		["turners logging camp"] = true,
		["twilights shroud"] = true,
		["wheelers grange"] = true,
		["windstead"] = true,
	},
	[2652] = {
		["bristleback retreat"] = true,
		["evenshades overlook"] = true,
		["forlorn gardens"] = true,
		["magram front"] = true,
		["outcast hideaway"] = true,
	},
}
