"""Quest givers' names as a client in another language shows them, for the quest log.

A play button in the quest log has no NPC to ask: the quest is already accepted, and the
giver is wherever the player left them. The addon finds the giver in the pack's lookup tables
(NPCIDLookupByQuestID and its object and item twins) and names them from
NPCNameLookupByNPCID -- which is built from the English corpus, so a German client's player
read "Farmer Furlbrow" under a German quest title, where the dialog, which asks the live
unit, reads "Bauer Furlbrow".

So the addon itself ships every other language's names for those givers, one file per
language that returns before it builds anything on a client in another one. Not the packs:
the name is what the *client* shows, whatever language the player chose to hear, and most
players on a German client install the English packs. And a pack is ~300 MB to re-release
for a name, where the addon is a few hundred kilobytes.

Only names that differ from the English are written. vmangos leaves a locale column empty
where the name is not translated -- "Eagan Peltskinner" is Eagan Peltskinner in German too --
and the English table already answers for those.

Nothing here needs a database: this picks the givers and writes the files, and corpus_db
does the query.
"""
import os

from tts_cli.build import build_tables


HEADER = """\
-- Generated by `make quests-export-giver-names` from entity_name; do not edit.
--
-- {lang} names of the quest givers the quest log's play buttons can name. The dialog asks
-- the live unit for its name, in the client's language; the quest log has no unit and
-- used the pack's English names. See pipelines/quests/tts_cli/giver_names.py.
if not (VoiceOver and VoiceOver.SpokenDialogue) then return end
setfenv(1, VoiceOver)

if GetLocale() ~= "{lang}" then
    return
end

"""


#: kind -> (the pack's questlog table, the pack's name table), as build_tables names them.
PACK_TABLES = {
    "creature": ("questlog_npc_lookups", "npc_name_lookups"),
    "gameobject": ("questlog_object_lookups", "object_name_lookups"),
    "item": ("questlog_item_lookups", "item_name_lookups"),
}
#: The kinds of quest giver the pack's questlog tables carry, as entity_name names them.
KINDS = tuple(PACK_TABLES)


def givers(corpus: dict, ignored=()) -> dict:
    """{(kind, entity id): English name} for every giver the questlog tables can name.

    Read off the pack's own tables, so a giver is exactly one the pack can hand the quest log
    and the English is exactly the name it would show. Ids are strings, as entity_name keys
    them.
    """
    tables = build_tables(corpus, ignored)
    found = {}
    for kind, (questlog, names) in PACK_TABLES.items():
        english = tables[names][1]
        for entity_id in set(tables[questlog][1].values()):
            found[(kind, str(entity_id))] = english[entity_id]
    return found


def localized_names(givers: dict, names: dict) -> dict:
    """{kind: {int id: name}} for one language, only where it differs from the English.

    `givers` is what givers() returns and `names` is {(kind, entity id): name}, the
    language's names from entity_name.
    """
    table = {kind: {} for kind in KINDS}
    for key, name in names.items():
        if key in givers and name and name != givers[key]:
            kind, entity_id = key
            table[kind][int(entity_id)] = name
    return table


def lua_string(text: str) -> str:
    """A Lua string literal. slpp leaves backslashes as they are, which a name may hold."""
    escaped = (text.replace("\\", "\\\\").replace('"', '\\"')
               .replace("\r", "\\r").replace("\n", "\\n"))
    return f'"{escaped}"'


def render(lang: str, table: dict) -> str:
    """One language's file. Sorted, so an export that changed nothing is the same file."""
    out = [HEADER.format(lang=lang), "GiverNames = {\n"]
    for kind in KINDS:
        out.append(f"    {kind} = {{\n")
        for entity_id in sorted(table[kind]):
            out.append(f"        [{entity_id}] = {lua_string(table[kind][entity_id])},\n")
        out.append("    },\n")
    out.append("}\n")
    return "".join(out)


def write_giver_names(out_dir: str, lang: str, table: dict) -> str:
    """Write `out_dir`/`lang`.lua and return its path."""
    os.makedirs(out_dir, exist_ok=True)
    path = os.path.join(out_dir, lang + ".lua")
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(render(lang, table))
    return path


def write_names_xml(out_dir: str, langs: list) -> str:
    """The Names.xml addon.xml includes, listing the files this export wrote.

    Written with them, so a language the export gains is loaded without a hand edit to
    addon.xml, and one it loses is not left listed.
    """
    lines = ['<Ui xsi:schemaLocation="http://www.blizzard.com/wow/ui/ ..\\FrameXML\\UI.xsd">',
             "    <!-- Generated by `make quests-export-giver-names`; do not edit. -->"]
    lines += [f'    <Script file="{lang}.lua"/>' for lang in langs]
    lines.append("</Ui>")
    path = os.path.join(out_dir, "Names.xml")
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    return path
