"""What an NPC's gossip reads as on every other client, and which stems are one moment.

The addon finds a gossip line from the NPC's text as the client shows it. The packs' tables
are English, so a client in another language needs that language's text for each line. This
writes it into the addon itself, one file per client locale, each of which returns before it
builds anything on a client in another locale. Not into the packs: the text follows the
client, not the voice the player chose, so a German client playing English packs needs the
German table, and an English client playing German packs needs none.

A line's text in a language comes from three places, all pointing at the line's stem:

  * its translation row, while that row still translates the line's current English;
  * the line itself, when it has no English and was written in that language;
  * BroadcastText in that language, for each id the line has (gossip_broadcast). The game
    stores a male and a female form, and the speaker's sex picks the one shown.

GossipAliases ties the stems of one moment together: lines that share an id and a voice, and
a line merged into another (gossip_merge), whose file only plays this way. The addon tries a
line's own stem first and its aliases after, so audio recorded under a sibling still plays. A
stem carrying a flavor (the broadcast form) is only tied to stems with the same flavor or none.
The pack build reads the same aliases (corpus/gossip_aliases.json) to ship those files.

Nothing here needs a database: corpus_db.export_gossip_text does the queries.
"""
import json
import os

from tts_cli.build import escape_lua_string
from tts_cli.giver_names import lua_string
from tts_cli.naming import gossip_hash_from_line_id, gossip_stem_rank

#: Every client locale but English, whose text is the packs' own tables. Italian is no
#: client's locale.
CLIENT_LOCALES = ("deDE", "esES", "esMX", "frFR", "koKR", "ptBR", "ruRU", "zhCN", "zhTW")

#: kind -> the addon table it is filed under, as the packs name them.
TABLES = {"creature": "GossipLookupByNPCID", "gameobject": "GossipLookupByObjectID"}

HEADER = """\
-- Generated by `make quests-export-gossip-text`; do not edit.
--
-- {lang} gossip text for every line, pointing at the file each line is named after, so a
-- client in {lang} finds gossip whatever language its packs speak. See
-- pipelines/quests/tts_cli/gossip_text.py.
if not SpokenGossipEnv then return end
-- DataModules, in Spoken's dialogue core, looks it up there.
setfenv(1, SpokenGossipEnv.Core)

if GetLocale() ~= "{lang}" then
    return
end

"""

ALIASES_HEADER = """\
-- Generated by `make quests-export-gossip-text`; do not edit.
--
-- The other files a gossip line's moment is recorded under: same BroadcastText id, same
-- voice. Tried after the line's own file. See pipelines/quests/tts_cli/gossip_text.py.
if not SpokenGossipEnv then return end
-- DataModules, in Spoken's dialogue core, looks it up there.
setfenv(1, SpokenGossipEnv.Core)

"""


def _order(line_id: str):
    return gossip_stem_rank(gossip_hash_from_line_id(line_id)), line_id


def broadcast_form(texts: tuple, gender: str) -> str:
    """The form of a BroadcastText row a speaker of this sex shows: (male, female) forms."""
    male, female = texts
    return (female or male) if gender == "female" else (male or female)


def gossip_text_tables(speakers: dict, english: dict, translations: dict, natives: dict,
                       broadcast_ids: dict, broadcast_texts: dict, ignored=()) -> dict:
    """{lang: {kind: {npc id: {client text: stem}}}} for every client locale.

    speakers        {lineId: [(npcType, npcId, race, gender, flavor), ...]}
    english         {lineId: current English originalText}
    translations    {lang: [(lineId, originalText it translates, localeText), ...]}
    natives         {lang: {lineId: text}}, lines with no English, in their own language
    broadcast_ids   {lineId: [broadcastTextId, ...]}
    broadcast_texts {lang: {broadcastTextId: (male form, female form)}}

    A text two lines of one NPC share goes to the preferred stem (broadcast, English,
    localized), so the choice does not depend on query order.
    """
    texts = {lang: {} for lang in CLIENT_LOCALES}
    for lang in CLIENT_LOCALES:
        for line_id, original, text in translations.get(lang, ()):
            if english.get(line_id) == original:
                texts[lang].setdefault(line_id, []).append(("any", text))
        for line_id, text in natives.get(lang, {}).items():
            if line_id not in english:
                texts[lang].setdefault(line_id, []).append(("any", text))
        forms = broadcast_texts.get(lang, {})
        for line_id, ids in broadcast_ids.items():
            for broadcast_id in ids:
                if broadcast_id in forms:
                    texts[lang].setdefault(line_id, []).append(("bt", forms[broadcast_id]))

    tables = {}
    for lang in CLIENT_LOCALES:
        table = {kind: {} for kind in TABLES}
        for line_id in sorted(texts[lang], key=_order):
            if line_id in ignored:
                continue
            stem = gossip_hash_from_line_id(line_id)
            for kind, npc_id, _race, gender, _flavor in speakers.get(line_id, ()):
                if kind not in table:
                    continue
                for how, text in texts[lang][line_id]:
                    shown = broadcast_form(text, gender) if how == "bt" else text
                    if shown:
                        table[kind].setdefault(npc_id, {}).setdefault(
                            escape_lua_string(shown), stem)
        tables[lang] = table
    return tables


#: What the pack build reads to ship each gossip file's aliases beside it.
DEFAULT_ALIASES_PATH = "corpus/gossip_aliases.json"


def gossip_aliases(speakers: dict, broadcast_ids: dict, ignored=(), merges=()) -> dict:
    """{stem: [the other stems of its moment, preferred first]}, only for stems that have any.

    Preferred: broadcast, English, localized, and within those the one voiced in the line's
    own flavor first. `merges` is [(merged lineId, lineId it went into)], whose files come
    after the moment's own.
    """
    moments = {}
    for line_id, ids in broadcast_ids.items():
        if line_id in ignored:
            continue
        stem = gossip_hash_from_line_id(line_id)
        carries = gossip_stem_rank(stem) == 0
        for _kind, _npc, race, gender, flavor in speakers.get(line_id, ()):
            for broadcast_id in ids:
                moments.setdefault((broadcast_id, race, gender), set()).add(
                    (stem, flavor, carries))

    aliases = {}
    for members in moments.values():
        for stem, flavor, carries in members:
            for other, other_flavor, other_carries in members:
                if other != stem and (flavor == other_flavor
                                      or not (carries and other_carries)):
                    key = (gossip_stem_rank(other), other_flavor != flavor, other)
                    aliases.setdefault(stem, {})[other] = min(
                        key, aliases.get(stem, {}).get(other, key))
    ordered = {stem: [other for other, _ in sorted(others.items(), key=lambda kv: kv[1])]
               for stem, others in aliases.items()}
    for merged, into in sorted(merges):
        stem, other = gossip_hash_from_line_id(into), gossip_hash_from_line_id(merged)
        if other not in ordered.setdefault(stem, []):
            ordered[stem].append(other)
    return dict(sorted(ordered.items()))


def write_aliases_json(path: str, aliases: dict) -> str:
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        json.dump(aliases, f, indent=1, sort_keys=True, ensure_ascii=False)
        f.write("\n")
    return path


def load_aliases(path: str = DEFAULT_ALIASES_PATH) -> dict:
    """The aliases export-gossip-text wrote, or none before it ever ran."""
    if not os.path.exists(path):
        return {}
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def render(lang: str, table: dict) -> str:
    """One locale's file. Sorted, so an export that changed nothing is the same file."""
    out = [HEADER.format(lang=lang), "GossipText = {\n"]
    for kind, name in TABLES.items():
        out.append(f"    {name} = {{\n")
        for npc_id in sorted(table[kind]):
            out.append(f"        [{npc_id}] = {{\n")
            for text in sorted(table[kind][npc_id]):
                out.append(f"            [{lua_string(text)}] = "
                           f"{lua_string(table[kind][npc_id][text])},\n")
            out.append("        },\n")
        out.append("    },\n")
    out.append("}\n")
    return "".join(out)


def render_aliases(aliases: dict) -> str:
    out = [ALIASES_HEADER, "GossipAliases = {\n"]
    for stem, others in aliases.items():
        out.append(f"    [{lua_string(stem)}] = {{ "
                   + ", ".join(lua_string(o) for o in others) + " },\n")
    out.append("}\n")
    return "".join(out)


def write_gossip_text(out_dir: str, tables: dict, aliases: dict) -> list:
    """Every locale's file, Aliases.lua and the Gossip.xml that loads them. Returns the paths."""
    os.makedirs(out_dir, exist_ok=True)
    files = {f"{lang}.lua": render(lang, tables[lang]) for lang in CLIENT_LOCALES}
    files["Aliases.lua"] = render_aliases(aliases)
    files["Gossip.xml"] = "\n".join(
        ['<Ui xsi:schemaLocation="http://www.blizzard.com/wow/ui/ ..\\FrameXML\\UI.xsd">',
         "    <!-- Generated by `make quests-export-gossip-text`; do not edit. -->",
         *(f'    <Script file="{name}"/>' for name in files),
         "</Ui>"]) + "\n"
    paths = []
    for name, content in files.items():
        path = os.path.join(out_dir, name)
        with open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write(content)
        paths.append(path)
    return paths
