if not (VoiceOver and VoiceOver.SpokenDialogue) then return end
setfenv(1, VoiceOver)

-- Generated by pipelines/quests/tools/export_followup_lines.py; do not edit by hand.
-- The world DB's quest start/end scripts make NPCs speak in chat after a quest is
-- accepted or turned in. The client never sees those lines as quest text, so this is
-- how the addon recognises them. speaker is a creature entry, absent when unresolved.
-- step is the script step a line is one outcome of: once one is heard, the rest of
-- its step never will be.
FollowupLines = {
    ["end"] = {
        [112] = { -- Collecting Kelp
            { id = 1851, step = 1, speaker = 253, delay = 0, chat = "say", male = "This shouldn't take long..." },
            { id = 1853, step = 2, speaker = 253, delay = 6, chat = "say", male = "The invisibility liquor is ready for you, $n." },
        },
        [114] = { -- The Escape
            { id = 1862, step = 1, speaker = 251, delay = 2, chat = "say", male = "Here goes nothing..." },
        },
        [166] = { -- The Defias Brotherhood
            { id = 197, step = 1, speaker = 234, delay = 1, chat = "yell", male = "All hail, $n! Defender of The People!" },
            { id = 198, step = 1, speaker = 234, delay = 1, chat = "yell", male = "The People of Westfall salute $n, a brave and valiant defender of freedom." },
            { id = 199, step = 1, speaker = 234, delay = 1, chat = "yell", male = "Three cheers for $n!  This land shall be ours once again!" },
        },
        [231] = { -- A Daughter's Love
            { id = 1014, step = 1, speaker = 3301, delay = 4, chat = "say", male = "My sword Archeus served me well in life, but as at last my spirit may pass from the unhappy existence, I need it no longer." },
            { id = 1015, step = 2, speaker = 3301, delay = 10, chat = "say", male = "I shall cling to the love of my daughter and hope that I will find forgiveness under the Light for my sins." },
        },
        [283] = { -- A Dark Threat Looms
            { id = 546, step = 1, speaker = 1093, delay = 1, chat = "yell", male = "The Stonewrought Dam has been saved!  Three cheers for $n!" },
        },
        [308] = { -- Distracting Jarven
            { id = 125, step = 1, speaker = 1373, delay = 25, chat = "say", male = "Hey there, Belm!  Give me a mug of Thunder Ale, and one for my good friend $n." },
        },
        [333] = { -- Harlan Needs a Resupply
            { id = 253, step = 1, speaker = 1428, delay = 3, chat = "say", male = "Corbett, dear.  Harlan needs a load of knitted shirts and pants as soon as we can manage." },
            { id = 254, step = 1, speaker = 1428, delay = 3, chat = "say", male = "Corbett, you there?  Harlan needs another load of knitted goods.  Can you take it to him?" },
            { id = 255, step = 2, speaker = 1433, delay = 7, chat = "say", male = "My pleasure, sugar drop.  I'll be back soon..." },
            { id = 256, step = 2, speaker = 1433, delay = 7, chat = "say", male = "Business must be good down at the bazaar.  I'll get him resupplied right away!" },
        },
        [336] = { -- A Noble Brew
            { id = 387, step = 1, speaker = 1439, delay = 1, chat = "say", male = "My, that Black Claw stout packs quite a punch!" },
            { id = 388, step = 2, speaker = 1439, delay = 6, chat = "say", male = "I feel... dizzy.  It's so hot... in... here..." },
        },
        [346] = { -- Return to Kristoff
            { id = 282, step = 1, speaker = 1444, delay = 1, chat = "say", male = "Thank you, $n.  May the Light bless you, $Gbrother:sister;, and guide your path." },
        },
        [407] = { -- Fields of Grief
            { id = 425, step = 1, speaker = 1931, delay = 0, chat = "say", male = "I. . .I. . .don't. . .feel. . .right. . ." },
            { id = 428, step = 2, speaker = 1931, delay = 6, chat = "say", male = "My mind. . .my flesh. . .I'm. . .rotting. . . .!" },
        },
        [411] = { -- The Prodigal Lich Returns
            { id = 1974, step = 1, speaker = 5666, delay = 15, chat = "say", male = "When time permits, we must speak at length.  For we have much to discuss." },
            { id = 1975, step = 2, speaker = 5666, delay = 19, chat = "say", male = "And thank you, $n.  Without your aid I may never have found my way to the Forsaken." },
            { id = 1976, step = 3, speaker = 1498, delay = 23, chat = "say", male = "Farewell, my friend." },
        },
        [412] = { -- Operation Recombobulation
            { id = 1883, step = 1, speaker = 1269, delay = 1, chat = "say", male = "Let me install these Gyromechanic Gears and Restabilization Cogs and we'll fire up The Recombobulator." },
        },
        [444] = { -- Rot Hide Origins
            { id = 514, step = 1, speaker = 1498, delay = 8, chat = "say", male = "No!  It can't be..." },
            { id = 515, step = 2, speaker = 1498, delay = 10, chat = "say", male = "Incredible!  I know he who wrought these enchantments..." },
            { id = 516, step = 2, speaker = 1498, delay = 10, chat = "say", male = "This is unforseen.  The being who enchanted this is known to me..." },
        },
        [489] = { -- Seek Redemption!
            { id = 886, step = 1, speaker = 2150, delay = 2, chat = "say", male = "Ribbit! No!! This cannot...ribbit...be! You have duped me with...ribbit...your foul trickery! Ribbit!" },
        },
        [492] = { -- A New Plague
            { id = 576, step = 1, speaker = 2211, delay = 0, chat = "say", male = "I raise my brew and hope to be rid of the likes of you!  Cheers, you no good scoundrel, $n!" },
        },
        [582] = { -- Headhunting
            { id = 734, step = 1, speaker = 2497, delay = 19, chat = "say", male = "I am done inspecting the skulls, $n, and I am relieved.  Yenniku is not among them..." },
        },
        [584] = { -- Bloodscalp Clan Heads
            { id = 735, step = 1, speaker = 2519, delay = 2, chat = "say", male = "Ah, good $n.  Now let us see what tale these heads tell..." },
            { id = 740, step = 2, speaker = 2519, delay = 12, chat = "say", male = "There, $N.  You may speak now speak to the Bloodscalp chief and his witchdoctor." },
        },
        [591] = { -- The Mind's Eye
            { id = 743, step = 1, speaker = 2519, delay = 8, chat = "say", male = "I have fashioned Yenniku's Soul Gem, $n..." },
        },
        [602] = { -- Magical Analysis
            { id = 761, step = 1, speaker = 2543, delay = 5, chat = "say", male = "How interesting... the Stone possesses great magical potential, but in a purely raw form..." },
        },
        [621] = { -- Zanzil's Secret
            { id = 1469, step = 1, speaker = 2498, delay = 0, chat = "say", male = "Thank you, $n." },
            { id = 1470, step = 2, speaker = 2498, delay = 3, chat = "say", male = "I'm sure I can find a use for this mixture..." },
        },
        [630] = { -- Message in a Bottle
            { id = 765, step = 1, speaker = 2634, delay = 5, chat = "say", male = "Thank you again for your aid. May the wind always be at your back during your travels." },
        },
        [637] = { -- Sully Balloo's Letter
            { id = 793, step = 1, speaker = 2695, delay = 6, chat = "say", male = "This isn't fair!  My dearest Sully!  Come back to me!  No, $n!  Why did you bring me such news!" },
        },
        [640] = { -- The Broken Sigil
            { id = 798, step = 1, speaker = 2706, delay = 6, chat = "say", male = "Easier than I expected... the sigil of Thoradin is whole, once again." },
        },
        [670] = { -- Sunken Treasure
            { id = 857, step = 1, speaker = 2610, delay = 1, chat = "say", male = "Wait, $n!!! It looks like we're going to need some help here..." },
        },
        [682] = { -- Stromgarde Badges
            { id = 874, step = 1, speaker = 2700, delay = 4, chat = "say", male = "Privates Marcus, Tremane, Osgood, Lampret..." },
            { id = 875, step = 1, speaker = 2700, delay = 4, chat = "say", male = "Privates Fontane, MacDugal, Wilcott..." },
            { id = 876, step = 1, speaker = 2700, delay = 4, chat = "say", male = "Privates Theoric, Kitrin, Blythe, Agmond..." },
            { id = 877, step = 1, speaker = 2700, delay = 4, chat = "say", male = "Privates Horus, Tilling, Rockwell..." },
            { id = 878, step = 2, speaker = 2700, delay = 8, chat = "say", male = "...Sampson, Yorick, Chamley..." },
            { id = 879, step = 2, speaker = 2700, delay = 8, chat = "say", male = "Clemens, Bartholemew, Enderman, Wyles..." },
            { id = 880, step = 2, speaker = 2700, delay = 8, chat = "say", male = "Tormil, Gamlor, Shefferd, Cowry..." },
            { id = 881, step = 2, speaker = 2700, delay = 8, chat = "say", male = "Martens, Reblock, Adinay, Nikeson..." },
            { id = 883, step = 3, speaker = 2700, delay = 13, chat = "say", male = "So many lost.  And so many more we must lose before this battle ends." },
            { id = 884, step = 4, speaker = 2700, delay = 16, chat = "say", male = "Thank you for these badges, $n.  I will send news to the families of the deceased." },
        },
        [689] = { -- A King's Tribute
            { id = 3501, step = 1, speaker = 2790, delay = 1, chat = "say", male = "I'll get to work right away, $n!" },
            { id = 3502, step = 2, speaker = 2790, delay = 22, chat = "say", male = "There you have it! The King should be quite pleased, if I do say so myself." },
            { id = 3503, step = 3, speaker = 2790, delay = 26, chat = "say", male = "The King's guards should be along shortly to pick up the Memorial. In the meantime, come join me upstairs and let's finish our little chat, $n." },
        },
        [692] = { -- The Lost Fragments
            { id = 871, step = 1, speaker = 2785, delay = 7, chat = "say", male = "Ah!  There is my ratchet!  Now let's re-attach these scroll fragments." },
            { id = 872, step = 2, speaker = 2785, delay = 13, chat = "say", male = "There we are, $n.  The Scroll is fixed!  Hooray!" },
        },
        [702] = { -- Guile of the Raptor
            { id = 861, step = 1, speaker = 2792, delay = 5, chat = "say", male = "What is this power that flows through me? Is this the power of shamanism that Tor'gan spoke of...?" },
            { id = 862, step = 2, speaker = 2792, delay = 8, chat = "say", male = "Amazing! I feel... renewed. My strength returns!" },
        },
        [705] = { -- Pearl Diving
            { id = 1023, step = 1, speaker = 2817, delay = 3, chat = "say", male = "There we are.  A new batch of flash bombs!" },
            { id = 1022, step = 2, speaker = 2817, delay = 7, chat = "say", male = "Look out!  We're under attack by a $n!" },
            { id = 1024, step = 3, speaker = 2817, delay = 10, chat = "say", male = "Take that, beast!" },
        },
        [709] = { -- Solution to Doom
            { id = 915, step = 1, speaker = 2785, delay = 3, chat = "say", male = "Aha!  That's it!" },
        },
        [724] = { -- Prospect of Faith
            { id = 917, step = 1, speaker = 2916, delay = 5, chat = "say", male = "Hammertoe, you're as smart as you were stubborn in life and even in death. What can you tell me, ole friend?" },
            { id = 916, step = 2, speaker = 2915, delay = 10, chat = "say", male = "Karnik, me friend, I wish I could see you with me own eyes again, but we need'ta talk of Ragnaros. His influence is spreading." },
            { id = 956, step = 3, speaker = 2916, delay = 15, chat = "say", male = "Ragnaros? Terrible news indeed..." },
            { id = 918, step = 4, speaker = 2915, delay = 20, chat = "say", male = "I'll tell you more, Karnik, in time. But first, send this traveler'ta Belgrum--there's more business'ta attend to." },
            { id = 958, step = 5, speaker = 2916, delay = 25, chat = "say", male = "You heard him, traveler. Speak to me again when you're ready to speak to Belgrum." },
        },
        [735] = { -- The Star, the Hand and the Heart
            { id = 920, step = 1, speaker = 2786, delay = 3, chat = "say", male = "I thank you, $n.  My associates who will do great things with these..." },
        },
        [737] = { -- Forbidden Knowledge
            { id = 934, step = 1, speaker = 2785, delay = 5, chat = "say", male = "Ow.  Spicy." },
        },
        [748] = { -- Poison Water
            { id = 1009, step = 1, speaker = 2948, delay = 8, chat = "say", male = "I have created the totem.  You, $n, must cleanse the well." },
        },
        [756] = { -- Thunderhorn Totem
            { id = 954, step = 1, speaker = 2948, delay = 8, chat = "say", male = "The totem is made, $n." },
        },
        [759] = { -- Wildmane Totem
            { id = 1006, step = 1, speaker = 2948, delay = 8, chat = "say", male = "The totem is made.  The well may now be cleansed." },
        },
        [771] = { -- Rite of Vision
            { id = 1012, step = 1, speaker = 3054, delay = 6, chat = "say", male = "The Water of the Seers is ready for your consumption, $n." },
        },
        [806] = { -- Dark Storms
            { id = 985, step = 1, speaker = 3142, delay = 0, chat = "say", male = "We will suffer no demon's servant in our lands!" },
        },
        [808] = { -- Minshina's Skull
            { id = 983, step = 1, speaker = 3188, delay = 0, chat = "say", male = "I thank you, $n.  And my brother thanks you." },
        },
        [823] = { -- Report to Orgnil
            { id = 982, step = 1, speaker = 3142, delay = 4, chat = "say", male = "What??  The Burning Blade is spreading!  We must investigate!" },
        },
        [827] = { -- Skull Rock
            { id = 989, step = 1, speaker = 3208, delay = 6, chat = "say", male = "Argh!" },
            { id = 988, step = 2, speaker = 3208, delay = 9, chat = "say", male = "$n, unlocking the secret of these collars is beyond my skills..." },
        },
        [829] = { -- Neeru Fireblade
            { id = 991, step = 1, speaker = 3216, delay = 5, chat = "say", male = "Interesting, very interesting.  You found this in Durotar, $n?" },
            { id = 992, step = 1, speaker = 3216, delay = 5, chat = "say", male = "The collar is indeed infused with demonic power, $n.  This bodes ill for our people." },
            { id = 993, step = 1, speaker = 3216, delay = 5, chat = "say", male = "Hm...it is good that you brought this to me, $n." },
            { id = 994, step = 1, speaker = 3216, delay = 5, chat = "say", male = "A dangerous device this is, $n.  I am glad you brought it to my attention." },
        },
        [848] = { -- Fungal Spores
            { id = 1077, step = 1, speaker = 3390, delay = 8, chat = "say", male = "Ah, good.  These spores have rendered nicely.  Thank you, $n." },
            { id = 1078, step = 2, speaker = 3390, delay = 12, chat = "say", male = "Thank you for the spores, $n.  They are now prepared for transport." },
        },
        [857] = { -- The Tear of the Moons
            { id = 1026, step = 1, speaker = 3421, delay = 1, chat = "say", male = "The power of the Tear of the Moons is mine! Mine I say!" },
            { id = 1028, step = 2, speaker = 3421, delay = 7, chat = "say", male = "Power! Glorious power!" },
        },
        [865] = { -- Raptor Horns
            { id = 2078, step = 1, speaker = 3446, delay = 0, chat = "say", male = "Now let's try it..." },
            { id = 2079, step = 2, speaker = 3446, delay = 5, chat = "say", male = "Ugh!  That's terrible!" },
        },
        [873] = { -- Isha Awak
            { id = 1301, step = 1, speaker = 3388, delay = 0, chat = "say", male = "May the spirit of Isha Awak give you strength, $n." },
        },
        [880] = { -- Altered Beings
            { id = 1087, step = 1, speaker = 3448, delay = 5, chat = "say", male = "Hm..." },
            { id = 1088, step = 2, speaker = 3448, delay = 8, chat = "say", male = "Strange.  Very strange..." },
            { id = 1089, step = 3, speaker = 3448, delay = 12, chat = "say", male = "$N.  These shells tell me much, but I fear many more questions are now raised..." },
        },
        [881] = { -- Echeyakee
            { id = 1295, step = 1, speaker = 3338, delay = 0, chat = "say", male = "The spirit of Echeyakee flows through you, $n." },
        },
        [902] = { -- Samophlange
            { id = 4727, step = 1, speaker = 3442, delay = 1, chat = "say", male = "Ok, let's take a look at this thing..." },
            { id = 4728, step = 2, speaker = 3442, delay = 11, chat = "say", male = "Oh, darn..." },
        },
        [927] = { -- The Moss-twined Heart
            { id = 1127, step = 1, speaker = 2080, delay = 4, chat = "say", male = "$n, underneath the moss, this heart looks like a seed!" },
            { id = 1128, step = 2, speaker = 2080, delay = 8, chat = "say", male = "Let's try planting it in some of my special, prepared soil..." },
        },
        [930] = { -- The Glowing Fruit
            { id = 1157, step = 1, speaker = 2080, delay = 6, chat = "say", male = "Let's see how these seeds grow in my prepared soil..." },
        },
        [931] = { -- The Shimmering Frond
            { id = 1160, step = 1, speaker = 2080, delay = 3, chat = "say", male = "I hope this frond takes root..." },
        },
        [943] = { -- The Absent Minded Prospector
            { id = 1180, step = 1, speaker = 2911, delay = 6, chat = "say", male = "By the stars! A spirit has been summoned!" },
            { id = 1182, step = 2, speaker = 3582, delay = 8, chat = "say", male = "Who hath summoned forth Aman?" },
            { id = 1183, step = 3, speaker = 3582, delay = 12, chat = "say", male = "Ah, I see you toil with relics of the past." },
            { id = 1184, step = 4, speaker = 3582, delay = 16, chat = "say", male = "Be warned that even your creators are fallible." },
            { id = 1185, step = 5, speaker = 3582, delay = 20, chat = "say", male = "Digging too deep into your past might bring an abrupt end to your future." },
            { id = 1181, step = 6, speaker = 2911, delay = 26, chat = "say", male = "It's a mystery of the past indeed! But a key to our future!" },
        },
        [950] = { -- Return to Onu
            { id = 1218, step = 1, speaker = 3616, delay = 7, chat = "say", male = "Hmm..." },
        },
        [963] = { -- For Love Eternal
            { id = 1278, step = 1, speaker = 3644, delay = 4, chat = "say", male = "Anaya...? Do my eyes deceive me? Is it really you?" },
            { id = 1279, step = 2, speaker = 3843, delay = 9, chat = "say", male = "The ages have been cruel to you and I, my love, but be assured, it is, and at long last we are reunited." },
            { id = 1280, step = 3, speaker = 3644, delay = 13, chat = "say", male = "That the fates should be so cruel as to permit us only this after a thousand years apart..." },
            { id = 1281, step = 4, speaker = 3644, delay = 17, chat = "say", male = "Do you hate me, my love? That I was forced to destroy your living form, that your spirit be released from unhappy bondage." },
            { id = 1282, step = 5, speaker = 3843, delay = 21, chat = "say", male = "Let it not trouble your heart, beloved. You have freed me from slavery, and for that I love you all the more." },
            { id = 1283, step = 6, speaker = 3843, delay = 27, chat = "say", male = "Sadly, even this must be cut short... The ties that bind me to this world weaken, and pull me away..." },
            { id = 1286, step = 7, speaker = 3644, delay = 34, chat = "say", male = "No! Anaya... Anaya! Don't leave me! Please..." },
            { id = 1284, step = 8, speaker = 3843, delay = 40, chat = "say", male = "Farewell, Cerellean, until we are joined once again..." },
            { id = 1287, step = 9, speaker = 3644, delay = 45, chat = "say", male = "How, my love? How will I find the strength to face the ages of the world without you by my side..." },
        },
        [970] = { -- The Tower of Althalaxx
            { id = 1459, step = 1, speaker = 3663, delay = 1, chat = "say", male = "A simple enough task to break this soulstone!" },
            { id = 1471, step = 2, speaker = 4509, delay = 10, chat = "say", male = "In the throes of the Sundering, Ameth'Aran was at the whim of the terror that gripped the land. There was little hope for survival." },
            { id = 1472, step = 3, speaker = 4509, delay = 14, chat = "say", male = "Athrikus came to us. He told us that he could save us from harm. He cast a spell upon us to protect us from harm." },
            { id = 1474, step = 4, speaker = 4509, delay = 18, chat = "say", male = "When the shaking stopped, his true motives were revealed. We were trapped, and he was slowly draining our powers." },
            { id = 1497, step = 5, speaker = 4509, delay = 22, chat = "say", male = "There were hundreds imprisoned by his spell. Now only a few remain in their prisons. He would speak to us sometimes." },
            { id = 1498, step = 6, speaker = 4509, delay = 26, chat = "say", male = "He worried that his power weakened, that soon even we last of his precious soulgems would fade and die." },
            { id = 1473, step = 7, speaker = 3663, delay = 30, chat = "say", male = "Then we must put an end to Athrikus Narassin. Tell me, spirit, where might we find the other soulgems, to undo his magic?" },
            { id = 1475, step = 8, speaker = 4509, delay = 34, chat = "say", male = "His lieutenant, Ilkrud Magthrull possesses a tome which might indicate the location of the remaining soulgems." },
        },
        [985] = { -- How Big a Threat?
            { id = 1245, step = 1, speaker = 3693, delay = 2, chat = "say", male = "What was that noise? It sounded like a roar." },
            { id = 1227, step = 2, speaker = 3693, delay = 12, chat = "say", male = "Grimclaw?! Easy there, my friend... where is your master Volcor?" },
            { id = 1229, step = 3, speaker = 3693, delay = 17, chat = "say", male = "Whoa, whoa there, my friend. One moment..." },
            { id = 1230, step = 4, speaker = 3693, delay = 24, chat = "say", male = "There... that should help. Now, tell me what's happened, Grimclaw." },
            { id = 1232, step = 5, speaker = 3693, delay = 30, chat = "say", male = "I understand, my friend. I shall find someone to help your master. Go back to him now, or at least stay close." },
            { id = 1384, step = 6, speaker = 3693, delay = 35, chat = "say", male = "If you have the time, Grimclaw and his master Volcor could use your help. If you're interested, speak with me further..." },
        },
        [986] = { -- A Lost Master
            { id = 1247, step = 1, speaker = 3693, delay = 0, chat = "say", male = "I shall get started right away, $n." },
            { id = 1248, step = 2, speaker = 3693, delay = 3, chat = "say", male = "Now... where was my thread and needle. Ah! There it is..." },
        },
        [994] = { -- Escape Through Force
            { id = 1302, step = 1, speaker = 3694, delay = 9, chat = "say", male = "Terenthis, Raene sent me to find you. The Sentinels are in need of help in Ashenvale." },
            { id = 1305, step = 2, speaker = 3693, delay = 14, chat = "say", male = "Hello, Selarin. I'm afraid I cannot help you at the moment, but perhaps some of the adventurers here in Auberdine can..." },
            { id = 1303, step = 3, speaker = 3694, delay = 20, chat = "say", male = "Thank you, Terenthis. I shall remain here for as long as I can." },
            { id = 1304, step = 4, speaker = 3694, delay = 25, chat = "say", male = "Hopefully I can send a worthy few to help Ashenvale and the Sentinels." },
        },
        [995] = { -- Escape Through Stealth
            { id = 1302, step = 1, speaker = 3694, delay = 9, chat = "say", male = "Terenthis, Raene sent me to find you. The Sentinels are in need of help in Ashenvale." },
            { id = 1305, step = 2, speaker = 3693, delay = 14, chat = "say", male = "Hello, Selarin. I'm afraid I cannot help you at the moment, but perhaps some of the adventurers here in Auberdine can..." },
            { id = 1303, step = 3, speaker = 3694, delay = 20, chat = "say", male = "Thank you, Terenthis. I shall remain here for as long as I can." },
            { id = 1304, step = 4, speaker = 3694, delay = 25, chat = "say", male = "Hopefully I can send a worthy few to help Ashenvale and the Sentinels." },
        },
        [997] = { -- Denalan's Earth
            { id = 1239, step = 1, speaker = 2080, delay = 1, chat = "say", male = "Now let us place this rare earth in my planter..." },
            { id = 1240, step = 2, speaker = 2080, delay = 9, chat = "say", male = "Thank you again, $n.  This rare earth will be very helpful in my experiments." },
        },
        [1007] = { -- The Ancient Statuette
            { id = 1325, step = 1, speaker = 3846, delay = 2, chat = "say", male = "This statuette must hold a hidden compartment..." },
            { id = 1326, step = 2, speaker = 3846, delay = 9, chat = "say", male = "It's locked!  NO!!" },
            { id = 1355, step = 3, speaker = 3846, delay = 13, chat = "say", male = "$n, I am in need of your help once again." },
        },
        [1010] = { -- Bathran's Hair
            { id = 1308, step = 1, speaker = 3847, delay = 7, chat = "say", male = "The mixture is finished, $n.  Now we must save the child." },
        },
        [1011] = { -- Forsaken Diseases
            { id = 1316, step = 1, speaker = 3848, delay = 7, chat = "say", male = "Uh... the disease is potent.  And it attacks the mind..." },
            { id = 1318, step = 2, speaker = 3848, delay = 13, chat = "say", male = "I must... RESIST!" },
            { id = 1319, step = 3, speaker = 3848, delay = 20, chat = "say", male = "I have survived the poisons of the Forsaken, $n, and I know now what must be done." },
        },
        [1020] = { -- Orendil's Cure
            { id = 1335, step = 1, speaker = 3894, delay = 2, chat = "say", male = "Here you are, Relara.  Take this..." },
            { id = 1337, step = 2, speaker = 3892, delay = 8, chat = "say", male = "Uh... Father...?  Are you there?  I'm hungry... can I have some stew?" },
            { id = 1338, step = 3, speaker = 3894, delay = 9, chat = "say", male = "What?" },
            { id = 1339, step = 4, speaker = 3894, delay = 13, chat = "say", male = "You're awake??  Your cure must have worked!  Thank you, $n." },
        },
        [1027] = { -- Raene's Cleansing
            { id = 1380, step = 1, speaker = 3916, delay = 1, chat = "say", male = "The rod's design is simple. Dartol didn't use his arcane knowledge in its creation... it is more druidic in nature." },
            { id = 1381, step = 2, speaker = 3916, delay = 5, chat = "say", male = "Hehe... I made a pun, didn't I? Druidic in nature... I'm so funny." },
            { id = 1382, step = 3, speaker = 3916, delay = 9, chat = "say", male = "Now, then... the rod. Let's see about fixing it, shall we?" },
            { id = 1383, step = 4, speaker = 3916, delay = 16, chat = "say", male = "There! Now it just needs to be recharged..." },
        },
        [1033] = { -- Elune's Tear
            { id = 1439, step = 1, speaker = 3894, delay = 6, chat = "say", male = "Eat this, my daughter.  It will help you feel better." },
            { id = 1440, step = 2, speaker = 3894, delay = 10, chat = "say", male = "There you go..." },
            { id = 1442, step = 3, speaker = 3892, delay = 16, chat = "say", male = "Mmmmh..." },
        },
        [1035] = { -- Fallen Sky Lake
            { id = 1347, step = 1, speaker = 3894, delay = 3, chat = "say", male = "Here you are, Relara.  Drink this..." },
            { id = 1349, step = 2, speaker = 3892, delay = 9, chat = "say", male = "Mmh... my eyes are not so heavy now, father.  Can we go out and play?" },
            { id = 1350, step = 3, speaker = 3894, delay = 12, chat = "say", male = "Relara... you're awake?" },
            { id = 1351, step = 4, speaker = 3894, delay = 15, chat = "say", male = "Rest now, my daughter." },
        },
        [1052] = { -- Down the Scarlet Path
            { id = 1378, step = 1, speaker = 3980, delay = 6, chat = "say", male = "By the Light! This is not good. There's something you don't understand, $n." },
        },
        [1058] = { -- Jin'Zil's Forest Magic
            { id = 1406, step = 1, speaker = 3995, delay = 5, chat = "say", male = "Ah, feel the magic seep into the cave, my little elves... muhahaha." },
            { id = 1407, step = 2, speaker = 3995, delay = 13, chat = "say", male = "So much for the power of nature... muhahahaha." },
        },
        [1059] = { -- Reclaiming the Charred Vale
            { id = 1397, step = 1, speaker = 4048, delay = 3, chat = "say", male = "We must hurry." },
        },
        [1062] = { -- Goblin Invaders
            { id = 1425, step = 1, speaker = 4049, delay = 1, chat = "say", male = "The spirits of Stonetalon still rage, $n." },
            { id = 1426, step = 2, speaker = 4049, delay = 3, chat = "say", male = "I fear we may never soothe them..." },
        },
        [1063] = { -- The Elder Crone
            { id = 1417, step = 1, speaker = 4046, delay = 4, chat = "say", male = "You were right to come.  My wisdom will be yours." },
        },
        [1066] = { -- Blood of Innocents
            { id = 1422, step = 1, speaker = 2216, delay = 4, chat = "say", male = "There we are, $n.  The toxin is ready." },
        },
        [1067] = { -- Return to Thunder Bluff
            { id = 1424, step = 1, speaker = 3419, delay = 5, chat = "say", male = "The toxin is ready, $n." },
        },
        [1076] = { -- Devils in Westfall
            { id = 1437, step = 1, speaker = 4078, delay = 1, chat = "say", male = "This should only take a moment, $n." },
        },
        [1103] = { -- Call of Water
            { id = 3069, step = 1, speaker = 7007, delay = 1, chat = "say", male = "Come down to da shrine with Tiev. We'll put da sapta magics to work there." },
        },
        [1108] = { -- Indurium
            { id = 1501, step = 1, speaker = 4618, delay = 3, chat = "say", male = "Now let's heat up these flakes..." },
            { id = 1502, step = 2, speaker = 4618, delay = 7, chat = "say", male = "So far they're holding.  Let's turn up the heat..." },
            { id = 1503, step = 3, speaker = 4618, delay = 12, chat = "say", male = "By Orgrim!  This indurium can withstand massive heat!" },
            { id = 1504, step = 4, speaker = 4618, delay = 17, chat = "say", male = "A successful test!  $n, this indurium is some amazing stuff." },
        },
        [1112] = { -- Parts for Kravel
            { id = 1478, step = 1, speaker = 4452, delay = 10, chat = "say", male = "There, that should do it..." },
        },
        [1116] = { -- Dream Dust in the Swamp
            { id = 1550, step = 1, speaker = 773, delay = 7, chat = "say", male = "ACHOO!" },
            { id = 1550, step = 2, speaker = 773, delay = 10, chat = "say", male = "ACHOO!" },
            { id = 1551, step = 3, speaker = 773, delay = 12, chat = "say", male = "Wow!  $n, that dream dust is powerful stuff!" },
        },
        [1117] = { -- Rumors for Kravel
            { id = 1481, step = 1, speaker = 4452, delay = 8, chat = "say", male = "Hahah!  $n, you make quite a partner!" },
        },
        [1118] = { -- Back to Booty Bay
            { id = 1468, step = 1, speaker = 2498, delay = 6, chat = "say", male = "Hm... if you're looking to adle wits, $n, then the secret behind Zanzil's zombies might just do the trick!" },
        },
        [1119] = { -- Zanzil's Mixture and a Fool's Stout
            { id = 1489, step = 1, speaker = 4452, delay = 3, chat = "say", male = "This stout sure smells strong!" },
            { id = 1491, step = 2, speaker = 4452, delay = 7, chat = "say", male = "Let's have just a small taste..." },
            { id = 1492, step = 3, speaker = 4452, delay = 15, chat = "say", male = "Wait!  What am I thinking!  We have a job to do with this stuff." },
        },
        [1120] = { -- Get the Gnomes Drunk
            { id = 8242, step = 1, speaker = 4495, delay = 1, chat = "say", male = "Look at what $n brought us!  Let's drink up!" },
        },
        [1121] = { -- Get the Goblins Drunk
            { id = 8244, step = 1, speaker = 4496, delay = 1, chat = "say", male = "$n brought us booze!  Let's party!" },
        },
        [1137] = { -- News for Fizzle
            { id = 1496, step = 1, speaker = 4454, delay = 4, chat = "say", male = "Astounding!  So then indurium is the key!" },
        },
        [1169] = { -- Identifying the Brood
            { id = 1512, step = 1, speaker = 4501, delay = 11, chat = "say", male = "The brood of Onyxia!" },
        },
        [1176] = { -- Load Lightening
            { id = 1526, step = 1, speaker = 4630, delay = 2, chat = "say", male = "Okay, crew. Get to work on getting these bones installed." },
        },
        [1179] = { -- The Brassbolts Brothers
            { id = 1527, step = 1, speaker = 4453, delay = 3, chat = "say", male = "Thanks for the helmets, $n.  These will really reduce our medical bills..." },
        },
        [1220] = { -- Captain Vimes
            { id = 1672, step = 1, speaker = 4944, delay = 4, chat = "say", male = "By the Light!  This cursed spy was a good one!  I'm glad he's dead." },
            { id = 1673, step = 2, speaker = 4944, delay = 8, chat = "say", male = "Thank you for this report, $n.  It is now clear that we must tighten our patrols near Theramore." },
        },
        [1240] = { -- The Troll Witchdoctor
            { id = 1664, step = 1, speaker = 2519, delay = 0, chat = "say", male = "I am eager to hear what so angry an orc has to say..." },
            { id = 1666, step = 2, speaker = 2519, delay = 12, chat = "say", male = "Peer into the cauldron, $n.  Marg wishes to speak..." },
        },
        [1268] = { -- Suspicious Hoofprints
            { id = 1755, step = 1, speaker = 4926, delay = 0, chat = "say", male = "Kagoro, I require your presence!" },
        },
        [1271] = { -- Feast at the Blue Recluse
            { id = 1718, step = 1, speaker = 1141, delay = 1, chat = "say", male = "All hail $n, a $c of worth!" },
            { id = 1719, step = 2, speaker = 1141, delay = 5, chat = "say", male = "Behold!  The Blue Recluse holds a feast in $g his:her; honor!" },
            { id = 1736, step = 3, speaker = 3628, delay = 12, chat = "say", male = "Long live $n!" },
            { id = 1733, step = 4, speaker = 1311, delay = 14, chat = "say", male = "Hooray, $n!" },
        },
        [1284] = { -- Suspicious Hoofprints
            { id = 1753, step = 1, speaker = 4944, delay = 0, chat = "say", male = "Tesoran! I need someone--Falgran Hastil, preferably--to take care of $n's lead on the prints near the Shady Rest Inn." },
            { id = 1754, step = 2, speaker = 4948, delay = 6, chat = "say", male = "Right away, sir." },
            { id = 1752, step = 3, speaker = 5088, delay = 19, chat = "say", male = "Falgran Hastil reporting, sir. I will find where the hoofprints lead and report back to you." },
        },
        [1371] = { -- Gizmo for Warug
            { id = 2045, step = 1, speaker = 5398, delay = 1, chat = "say", male = "Hah!  Let us see the wooden human wave!" },
            { id = 2046, step = 2, speaker = 5398, delay = 10, chat = "say", male = "Hahah!  That was funny!  Funny wooden human!" },
        },
        [1383] = { -- Nothing But The Truth
            { id = 1848, step = 1, speaker = 5414, delay = 1, chat = "say", male = "The serum will only take a few minutes to prepare, $n." },
            { id = 1849, step = 2, speaker = 5414, delay = 10, chat = "say", male = "Almost done..." },
            { id = 1850, step = 3, speaker = 5414, delay = 16, chat = "say", male = "At last, the serum is complete, $n. Now, come closer. We must talk." },
        },
        [1391] = { -- Nothing But The Truth
            { id = 1858, step = 1, speaker = 5416, delay = 0, chat = "say", male = "That was refreshing. Now there's information that needs to be told..." },
            { id = 1859, step = 2, speaker = 5416, delay = 6, chat = "say", male = "I believe the Forsaken are misleading the allies of the Horde.... wait... I feel so... dizzy..." },
            { id = 1861, step = 3, speaker = 5416, delay = 12, chat = "say", male = "AAAAAAAAAAAAAAAARGH!" },
        },
        [1445] = { -- The Temple of Atal'Hakkar
            { id = 1949, step = 1, speaker = 1443, delay = 1, chat = "say", male = "I hereby destroy these instruments of evil! For the Horde!" },
        },
        [1452] = { -- Rhapsody's Kalimdor Kocktail
            { id = 1950, step = 1, speaker = 5634, delay = 1, chat = "say", male = "Time to brew up a Kalimdor Kocktail! Hiccup!" },
            { id = 1951, step = 2, speaker = 5634, delay = 12, chat = "say", male = "That should do it! Hiccup!" },
            { id = 1953, step = 3, speaker = 5634, delay = 22, chat = "say", male = "Hiccup!" },
            { id = 1954, step = 4, speaker = 5634, delay = 23, chat = "say", male = "Ok, who pushed me down? Was it you, $n? Someone turn the lights back on. Hiccup!" },
            { id = 1955, step = 5, speaker = 5634, delay = 35, chat = "say", male = "One more sip of the ol' fire water and I'll be ready to talk. Hiccup! Cheers!" },
            { id = 1956, step = 6, speaker = 5634, delay = 38, chat = "say", male = "So, $n, I'm ready to tell you what happened in the Swamp of Sorrows. Hiccup!" },
        },
        [1482] = { -- The Corrupter
            { id = 2085, step = 1, speaker = 4498, delay = 1, chat = "say", male = "This should only take a moment, $n." },
            { id = 2087, step = 2, speaker = 4498, delay = 3, chat = "say", male = "I call your true name, Azrethoc. Show your visage to me!" },
            { id = 2089, step = 3, speaker = 5773, delay = 7, chat = "say", male = "Pathetic Forsaken weakling. You wish to see my master? So be it." },
            { id = 2090, step = 4, speaker = 5772, delay = 12, chat = "say", male = "Who dares to seek me out?!" },
            { id = 2091, step = 5, speaker = 5772, delay = 15, chat = "say", male = "Insects!" },
            { id = 2092, step = 6, speaker = 5772, delay = 18, chat = "say", male = "Come! Come to your deaths--if you dare!" },
            { id = 2093, step = 7, speaker = 5773, delay = 20, chat = "say", male = "Yes, come. My master and I shall be waiting." },
            { id = 2094, step = 8, speaker = 4498, delay = 22, chat = "say", male = "An interesting turning of events." },
        },
        [1521] = { -- Call of Earth
            { id = 2184, step = 1, speaker = 5888, delay = 0, chat = "say", male = "Peace and patience be with you, $n. Remain strong always." },
        },
        [1527] = { -- Call of Fire
            { id = 2181, step = 1, speaker = 5907, delay = 1, chat = "say", male = "May your spirit burn brightly, $n." },
        },
        [1681] = { -- Ironband's Compound
            { id = 2304, step = 1, speaker = 6031, delay = 17, chat = "say", male = "$n!  I'm finished!" },
        },
        [1692] = { -- Smith Mathiel
            { id = 2307, step = 1, speaker = 6142, delay = 13, chat = "say", male = "It is done.  I have your weapon, $n." },
        },
        [1699] = { -- The Rethban Gauntlet
            { id = 2308, step = 1, speaker = 6166, delay = 0, chat = "yell", male = "$n ran the Gauntlet!  Three cheers for $n!" },
            { id = 2309, step = 2, speaker = 6166, delay = 5, chat = "say", male = "Hip hip, hoorah!" },
            { id = 2309, step = 3, speaker = 6166, delay = 9, chat = "say", male = "Hip hip, hoorah!" },
            { id = 2309, step = 4, speaker = 6166, delay = 13, chat = "say", male = "Hip hip, hoorah!" },
        },
        [1701] = { -- Fire Hardened Mail
            { id = 2342, step = 1, speaker = 5413, delay = 26, chat = "say", male = "Finished!  And the results are amazing.  I must convey them to my associates Grimand, Mathiel and Klockmort!" },
            { id = 2343, step = 2, speaker = 5413, delay = 34, chat = "say", male = "Your armor is ready, $n." },
        },
        [1705] = { -- Burning Blood
            { id = 2347, step = 1, speaker = 1416, delay = 13, chat = "say", male = "Amazing!  It worked!  $n, I have your armor." },
        },
        [1708] = { -- Iron Coral
            { id = 2345, step = 1, speaker = 6169, delay = 25, chat = "say", male = "Hooray hooray! $n! It's done!" },
        },
        [1710] = { -- Sunscorched Shells
            { id = 2349, step = 1, speaker = 6142, delay = 13, chat = "say", male = "It is done.  $n, your armor is ready." },
        },
        [1719] = { -- The Affray
            { id = 2354, step = 1, speaker = 6236, delay = 0, chat = "yell", male = "Hail $n!  New Champion of The Affray!" },
        },
        [1838] = { -- Brutal Armor
            { id = 2634, step = 1, speaker = 5878, delay = 37, chat = "say", male = "Your armor is ready, $n." },
        },
        [1842] = { -- Satyr Hooves
            { id = 2646, step = 1, speaker = 6408, delay = 18, chat = "say", male = "I am done.  Your armor is ready, $n." },
        },
        [1844] = { -- Chimaeric Horn
            { id = 2635, step = 1, speaker = 6410, delay = 17, chat = "say", male = "I have completed your helm, $n." },
        },
        [1846] = { -- Dragonmaw Shinbones
            { id = 2645, step = 1, speaker = 6411, delay = 17, chat = "say", male = "I have finished your leg guards, $n." },
        },
        [1921] = { -- Gathering Materials
            { id = 2647, step = 1, speaker = 1309, delay = 1, chat = "say", male = "These are fine pieces, $n.  Let me get started on your robe." },
            { id = 2648, step = 2, speaker = 1309, delay = 8, chat = "say", male = "That's it!  It's all finished, $n." },
        },
        [1940] = { -- Pristine Spider Silk
            { id = 2649, step = 1, speaker = 1309, delay = 1, chat = "say", male = "Ok, let's get to work!" },
            { id = 2651, step = 2, speaker = 1309, delay = 5, chat = "say", male = "Now where did I put that silver spool..." },
            { id = 2650, step = 3, speaker = 1309, delay = 9, chat = "say", male = "Aha!  There it is." },
            { id = 2648, step = 4, speaker = 1309, delay = 16, chat = "say", male = "That's it!  It's all finished, $n." },
        },
        [1945] = { -- Laughing Sisters
            { id = 2665, step = 1, speaker = 3484, delay = 1, chat = "say", male = "I shall now begin the robe..." },
            { id = 2666, step = 2, speaker = 3484, delay = 7, chat = "say", male = "Your robe is complete, $n." },
        },
        [1947] = { -- Journey to the Marsh
            { id = 2656, step = 1, speaker = 6546, delay = 1, chat = "say", male = "I just have one thing to check..." },
            { id = 2657, step = 2, speaker = 6546, delay = 13, chat = "say", male = "That's it!  It worked!" },
            { id = 2658, step = 3, speaker = 6546, delay = 16, chat = "say", male = "Thanks for your patience, $n." },
            { id = 2659, step = 4, speaker = 6546, delay = 20, chat = "say", male = "I'll just keep this here until we need it..." },
        },
        [1951] = { -- Rituals of Power
            { id = 2659, step = 1, speaker = 6546, delay = 0, chat = "say", male = "I'll just keep this here until we need it..." },
        },
        [1957] = { -- Mana Surges
            { id = 2663, step = 1, speaker = 6546, delay = 1, chat = "say", male = "Ok, let's get this orb made..." },
            { id = 2664, step = 2, speaker = 6546, delay = 8, chat = "say", male = "All right.  It's made!" },
        },
        [1961] = { -- Gathering Materials
            { id = 2761, step = 1, speaker = 4576, delay = 1, chat = "say", male = "One moment while I stitch this together..." },
            { id = 2762, step = 2, speaker = 4576, delay = 7, chat = "say", male = "There.  I am finished with your robe, $n." },
        },
        [2118] = { -- Plagued Lands
            { id = 5937, step = 1, speaker = 3701, delay = 2, chat = "say", male = "Be cleansed!" },
        },
        [2204] = { -- Restoring the Necklace
            { id = 3121, step = 1, speaker = 6826, delay = 0, chat = "say", male = "Let me grab a spell focus from inside my home here, and then we'll get started!" },
            { id = 3122, step = 2, speaker = 6826, delay = 10, chat = "say", male = "Bah, it isn't here.  Where did I have that blasted thing at last?" },
            { id = 3123, step = 3, speaker = 6826, delay = 13, chat = "say", male = "That's right, it's over by the bed.  Heh, sorry about that!" },
            { id = 3124, step = 4, speaker = 6826, delay = 21, chat = "say", male = "Fantastic then!  Let's get this thing fixed for you." },
            { id = 3125, step = 5, speaker = 6826, delay = 34, chat = "say", male = "Success!  Huzzah!  The power source restored the necklace!" },
        },
        [2278] = { -- The Platinum Discs
            { id = 3743, step = 1, speaker = 7172, delay = 0, chat = "yell", male = "Your discs are now ready!  Engage the Discs of Norgannon once again to retrieve them!" },
        },
        [2338] = { -- Translating the Journal
            { id = 3082, step = 1, speaker = 6868, delay = 0, chat = "say", male = "Allow me to get some water for the inking reagent." },
            { id = 3084, step = 2, speaker = 6868, delay = 6, chat = "say", male = "This will do nicely.  Now to the task at hand!" },
            { id = 3085, step = 3, speaker = 6868, delay = 13, chat = "say", male = "There we go, all finished.  The journal has been translated for you." },
        },
        [2339] = { -- Find the Gems and Power Source
            { id = 3083, step = 1, speaker = 6868, delay = 0, chat = "say", male = "And now for a quick look at these gems." },
            { id = 3091, step = 2, speaker = 6868, delay = 7, chat = "say", male = "Just as I thought, the gems and the necklace don't matter.  It's all about the power source." },
        },
        [2340] = { -- Deliver the Gems
            { id = 3077, step = 1, speaker = 6986, delay = 1, chat = "say", male = "Now we just need to figure out how to get this thing working again." },
            { id = 3078, step = 2, speaker = 6987, delay = 5, chat = "say", male = "Maybe I can fix it, pop.  Lemme take a look at it." },
            { id = 3080, step = 3, speaker = 6986, delay = 9, chat = "say", male = "Boy, you couldn't fix a sandwich without someone tellin' ya how to do it." },
            { id = 3079, step = 4, speaker = 6987, delay = 13, chat = "say", male = "Sandwich?  What?  You makin' a sandwich for me, pop?" },
            { id = 3081, step = 5, speaker = 6986, delay = 17, chat = "yell", male = "Malton, you dummy!" },
        },
        [2521] = { -- To Serve Kum'isha
            { id = 3475, step = 1, speaker = 7363, delay = 133, chat = "yell", male = "Success, the rift is open!! My brethren, rise and return home! The Outland awaits!" },
            { id = 3476, step = 2, speaker = 7363, delay = 148, chat = "say", male = "Hurry brothers! You must go now! I do not know how much longer the rift will remain open!" },
            { id = 3477, step = 3, speaker = 7363, delay = 175, chat = "say", male = "And now you know why I live in a crater." },
        },
        [2641] = { -- Sprinkle's Secret Ingredient
            { id = 3661, step = 1, speaker = 7583, delay = 0, chat = "say", male = "Just sit tight while I get this prepared for you!" },
        },
        [2939] = { -- In Search of Knowledge
            { id = 4042, step = 1, speaker = 7907, delay = 1, chat = "say", male = "Take a look around, $n. Perhaps you will find something that I have missed." },
        },
        [2943] = { -- Return to Troyas
            { id = 4039, step = 1, speaker = 7764, delay = 1, chat = "say", male = "Feralas: A History... Hmmmm... Let me examine this for a moment." },
            { id = 4041, step = 2, speaker = 7764, delay = 10, chat = "say", male = "Amazing! I think I have found it, $n!" },
        },
        [3122] = { -- Return to Witch Doctor Uzer'i
            { id = 4180, step = 1, speaker = 8115, delay = 29, chat = "say", male = "The muisek vessels are now ready, $n." },
        },
        [3182] = { -- Proof of Deed
            { id = 4305, step = 1, speaker = 8256, delay = 1, chat = "say", male = "I have just the spot for this horn!" },
        },
        [3364] = { -- Scalding Mornbrew Delivery
            { id = 4377, step = 1, speaker = 836, delay = 2, chat = "say", male = "There's nothing like some scalding mornbrew on a chilly Dun Morogh day to get things started right!" },
            { id = 4378, step = 2, speaker = 836, delay = 8, chat = "say", male = "Oooooo hot hot hot!  If that won't put spring in your step, I don't know what will!" },
        },
        [3379] = { -- Shadoweaver
            { id = 4415, step = 1, speaker = 8441, delay = 0, chat = "say", male = "Bye, bye, tiny little $r. Raze go now." },
        },
        [3448] = { -- Passing the Burden
            { id = 4451, step = 1, speaker = 8507, delay = 3, chat = "say", male = "Oh, $n, wait a minute! There's one more thing! Come back!" },
        },
        [3463] = { -- Set Them Ablaze!
            { id = 4456, step = 1, speaker = 8480, delay = 4, chat = "say", male = "Glorious, indeed, Maltrake. It looks as if my plan worked perfectly. Wouldn't you say so, mortal?" },
            { id = 4457, step = 2, speaker = 8480, delay = 10, chat = "say", male = "You would not have helped the legion of Blackrock had we just asked for your assistance, now would you?" },
            { id = 4459, step = 3, speaker = 8509, delay = 16, chat = "say", male = "What will we do with them, master? They are of no use to us anymore." },
            { id = 4460, step = 4, speaker = 8480, delay = 25, chat = "say", male = "SILENCE FOOL!" },
            { id = 4461, step = 5, speaker = 8480, delay = 31, chat = "say", male = "They will live, if only to see the fruits of their labor: the destruction and chaos that will surely ensue as the legion of Blackrock invade the gorge." },
            { id = 4462, step = 6, speaker = 8480, delay = 38, chat = "say", male = "I leave you now, mortals. Alive and with these trinkets. Maltrake! Present them with the trinkets!" },
            { id = 4468, step = 7, speaker = 8509, delay = 38, chat = "say", male = "Right away, master!" },
            { id = 4463, step = 8, speaker = 8480, delay = 47, chat = "say", male = "Oh yes, the molt - do not lose it. There are those of my kin in the Burning Steppes that would craft items that only the molt of the black Dragonflight could fortify." },
            { id = 4465, step = 9, speaker = 8480, delay = 54, chat = "yell", male = "The legion of Blackrock comes, dwarflings! We shall scorch the earth and set fire to the heavens. None shall survive..." },
        },
        [3568] = { -- Seeping Corruption
            { id = 4522, step = 1, speaker = 8390, delay = 5, chat = "say", male = "There! Job's done." },
        },
        [3569] = { -- Seeping Corruption
            { id = 4533, step = 1, speaker = 8393, delay = 4, chat = "say", male = "Wha... what's happening?" },
        },
        [3741] = { -- Hilary's Necklace
            { id = 4627, step = 1, speaker = 8963, delay = 1, chat = "say", male = "Meow!" },
            { id = 4628, step = 2, speaker = 8962, delay = 3, chat = "say", male = "I know how to speak kitty, and Effsee said thank you." },
        },
        [3906] = { -- Disharmony of Flame
            { id = 4717, step = 1, speaker = 9078, delay = 1, chat = "whisper", male = "You are indeed powerful, $n. Come to me if it is more work that you seek." },
            { id = 4718, step = 2, speaker = 9081, delay = 4, chat = "whisper", male = "My eyes never deceive me, $r. I see great power in you - enough power, perhaps, to further our cause. Find me at the top of the tower." },
        },
        [3908] = { -- It's a Secret to Everybody
            { id = 6153, step = 1, speaker = 9298, delay = 1, chat = "say", male = "Please, follow me." },
            { id = 6154, step = 2, speaker = 9298, delay = 15, chat = "say", male = "I haven't really figured out what it is, but there's something strange about the hot springs..." },
            { id = 6156, step = 3, speaker = 9298, delay = 26, chat = "say", male = "I've found that when I throw something into this water, it has improved incredibly when I retrieve it." },
            { id = 6157, step = 4, speaker = 9298, delay = 30, chat = "say", male = "Well, whatever it is, it works quite well!" },
            { id = 6158, step = 5, speaker = 9298, delay = 48, chat = "say", male = "And I am determined to find out more... So if you need my help again, you know where I'll be." },
        },
        [3922] = { -- Nugget Slugs
            { id = 4729, step = 1, speaker = 9316, delay = 0, chat = "say", male = "Ok!  Let's get started!" },
            { id = 4730, step = 2, speaker = 9316, delay = 10, chat = "say", male = "... oops." },
        },
        [3941] = { -- A Gnome's Assistance
            { id = 4839, step = 1, speaker = 9117, delay = 7, chat = "say", male = "I know it'll work this time..." },
            { id = 4840, step = 1, speaker = 9117, delay = 7, chat = "say", male = "This will be my best experiment yet!" },
            { id = 4841, step = 1, speaker = 9117, delay = 7, chat = "say", male = "Now, if I add the yellow ones..." },
            { id = 4842, step = 1, speaker = 9117, delay = 7, chat = "say", male = "I know it'll work this time... My last 13 tries were just practice!" },
            { id = 4847, step = 2, speaker = 9117, delay = 16, chat = "say", male = "I think... I think it's working!" },
            { id = 4852, step = 3, speaker = 9117, delay = 20, chat = "say", male = "OW! That's not right!" },
            { id = 4853, step = 4, speaker = 9117, delay = 23, chat = "say", male = "Oh well... Maybe next time." },
        },
        [4129] = { -- The Knife Revealed
            { id = 5148, step = 1, speaker = 7879, delay = 2, chat = "say", male = "I will need to focus my energies onto this knife.  By doing so, I should catch some of the stronger psychic impressions associated with it." },
            { id = 5149, step = 2, speaker = 7879, delay = 10, chat = "say", male = "I... I've seen enough I think... so very draining..." },
        },
        [4144] = { -- Bloodpetal Sprouts
            { id = 4966, step = 1, speaker = 9119, delay = 0, chat = "say", male = "I hope this works!" },
            { id = 4968, step = 2, speaker = 9119, delay = 15, chat = "say", male = "Look at them go!" },
        },
        [4451] = { -- The Key to Freedom
            { id = 5407, step = 1, speaker = 9876, delay = 3, chat = "say", male = "Ach! Thank you so much, $n! I'm free! Finally!" },
            { id = 5408, step = 2, speaker = 9876, delay = 6, chat = "say", male = "You take care of yourself! I'm gettin' out o' here." },
        },
        [4505] = { -- Well of Corruption
            { id = 5945, step = 1, speaker = 9996, delay = 1, chat = "say", male = "I'm very curious to see what this sample of water will do!" },
            { id = 5947, step = 2, speaker = 9996, delay = 9, chat = "say", male = "Haha! Perfect!" },
        },
        [4512] = { -- A Little Slime Goes a Long Way
            { id = 5447, step = 1, speaker = 9616, delay = 3, chat = "say", male = "Incredible! Amazing! I don't even know what this means!" },
        },
        [4621] = { -- Avast Ye, Admiral!
            { id = 5522, step = 1, speaker = 2546, delay = 0, chat = "yell", male = "Three cheers for $n -- Admiral o' the Bloodsail Bucaneer Navy!" },
            { id = 5523, step = 2, speaker = 2546, delay = 2, chat = "yell", male = "Hip hip... arrrrr..." },
            { id = 5523, step = 3, speaker = 2546, delay = 3, chat = "yell", male = "Hip hip... arrrrr..." },
            { id = 5523, step = 4, speaker = 2546, delay = 4, chat = "yell", male = "Hip hip... arrrrr..." },
        },
        [4974] = { -- For The Horde!
            { id = 6013, step = 1, speaker = 4949, delay = 3, chat = "yell", male = "Honor your heroes! On this day, they have dealt a great blow against one of our most hated enemies! The false Warchief, Rend Blackhand, has fallen!" },
            { id = 6014, step = 2, speaker = 4949, delay = 13, chat = "yell", male = "Be bathed in my power! Drink in my might! Battle for the glory of the Horde!" },
        },
        [5087] = { -- Winterfall Runners
            { id = 6232, step = 1, speaker = 9298, delay = 3, chat = "say", male = "Are you sure you weren't followed here? I have a very bad feeling all of a sudden..." },
        },
        [5149] = { -- Pamela's Doll
            { id = 6416, step = 1, speaker = 10926, delay = 1, chat = "say", male = "Hurray!  My doll!" },
            { id = 6417, step = 2, speaker = 10926, delay = 4, chat = "say", male = "You'll keep the bad people away, won't you?" },
        },
        [5154] = { -- The Annals of Darrowshire
            { id = 6418, step = 1, speaker = 10667, delay = 1, chat = "say", male = "Let's find out the whole story.  That's going to take some magic..." },
            { id = 6419, step = 2, speaker = 10667, delay = 7, chat = "say", male = "There, it is done.  The book has been enhanced..." },
        },
        [5247] = { -- Fragments of the Past
            { id = 8332, step = 1, speaker = 10304, delay = 1, chat = "say", male = "Please wait while I attempt to bind the shards together so that they will be whole once again." },
            { id = 8333, step = 2, speaker = 10304, delay = 10, chat = "say", male = "Ishnu... Oshalan thara dormil... Anu'dorin..." },
            { id = 8338, step = 3, speaker = 10304, delay = 36, chat = "say", male = "Yes, I was able to reseal the relic, $n." },
        },
        [5341] = { -- Barov Family Fortune
            { id = 6554, step = 1, speaker = 11022, delay = 1, chat = "yell", male = "The deeds are mine, brother! Soon you shall be out of my way for good!" },
        },
        [5343] = { -- Barov Family Fortune
            { id = 6555, step = 1, speaker = 11023, delay = 1, chat = "yell", male = "The fortune is mine, Alexi! Your end comes soon!" },
        },
        [5803] = { -- Araj's Scarab
            { id = 7278, step = 1, speaker = 11056, delay = 1, chat = "say", male = "The solution is ready in my cauldron.  It's just the matter of treating both the unfinished key and the scarab." },
            { id = 7279, step = 2, speaker = 11056, delay = 10, chat = "say", male = "It's done $n, and I think you'll be satisfied with the results." },
        },
        [5804] = { -- Araj's Scarab
            { id = 7278, step = 1, speaker = 11057, delay = 1, chat = "say", male = "The solution is ready in my cauldron.  It's just the matter of treating both the unfinished key and the scarab." },
            { id = 7279, step = 2, speaker = 11057, delay = 10, chat = "say", male = "It's done $n, and I think you'll be satisfied with the results." },
        },
        [5862] = { -- Scarlet Subterfuge
            { id = 7319, step = 1, speaker = 1836, delay = 0, chat = "say", male = "Sir?" },
            { id = 7321, step = 2, speaker = 1836, delay = 0, chat = "say", male = "What the..." },
            { id = 7322, step = 3, speaker = 1836, delay = 0, chat = "say", male = "Hey, what's going on over there? Sir, are you alright? Sir??" },
            { id = 7323, step = 4, speaker = 1836, delay = 0, chat = "say", male = "Highlord Fordring, are you alright?" },
            { id = 7320, step = 5, speaker = 1836, delay = 6, chat = "say", male = "Something is wrong with the Highlord. Do something!" },
            { id = 7318, step = 6, speaker = 1842, delay = 13, chat = "yell", male = "NOOOOOOOOOOOO!" },
        },
        [6661] = { -- Deeprun Rat Roundup
            { id = 8465, step = 1, speaker = 12997, delay = 2, chat = "say", male = "Into the box me pretties! Thas it. One by one ye go." },
        },
        [7496] = { -- Celebrating Good Times
            { id = 9495, step = 1, speaker = 14394, delay = 3, chat = "yell", male = "Citizens and allies of Stormwind, on this day, history has been made. $n has laid waste to that which had attempted to usurp the rule of the kingdom. Gather round and join me in honoring our heroes." },
            { id = 9496, step = 2, speaker = 14394, delay = 12, chat = "yell", male = "Behold the might of the Alliance! The dread lady, Onyxia, hangs from the arches! Let the rallying cry of the dragon slayer lift your spirits!" },
        },
        [7603] = { -- Kroshius' Infernal Core
            { id = 9634, step = 1, speaker = 14469, delay = 7, chat = "say", male = "Stand back! Stand clear! The infernal will need to be given a wide berth!" },
            { id = 9635, step = 2, speaker = 14469, delay = 10, chat = "say", male = "BOW DOWN TO THE ALMIGHTY! BOW DOWN BEFORE MY INFERNAL DESTRO... chicken?" },
            { id = 9637, step = 3, speaker = 14470, delay = 14, chat = "say", male = "Niby, you're an idiot." },
            { id = 9638, step = 4, speaker = 14469, delay = 17, chat = "say", male = "Silence, servant! Vengeance will be mine! Death to Stormwind! Death by chicken!" },
        },
        [7642] = { -- Collection of Goods
            { id = 9776, step = 1, speaker = 1416, delay = 2, chat = "say", male = "Follow me, good Paladin.  I'll have your barding done faster than I could down a Dwarven stout.  Mmmm... stout." },
        },
        [7782] = { -- The Lord of Blackrock
            { id = 9870, step = 1, speaker = 14721, delay = 3, chat = "yell", male = "Citizens of the Alliance, the Lord of Blackrock is slain! Nefarian has been subdued by the combined might of $n and $g his:her; allies!" },
            { id = 9872, step = 2, speaker = 14721, delay = 14, chat = "yell", male = "Let your spirits rise! Rally around your champion, bask in $g his:her; glory! Revel in the rallying cry of the dragon slayer!" },
        },
        [7846] = { -- Recover the Key!
            { id = 10013, step = 1, speaker = 14757, delay = 5, chat = "say", male = "Finally, I am free! I come home soon, my dear!" },
        },
        [8183] = { -- The Heart of Hakkar
            { id = 10473, step = 1, speaker = 14875, delay = 0, chat = "say", male = "Now, only one step remains to rid us of the Soulflayer's threat..." },
            { id = 10474, step = 2, speaker = 14875, delay = 22, chat = "yell", male = "Begin the ritual, my servants.  We must banish the heart of Hakkar back into the void!" },
            { id = 10537, step = 3, speaker = 14875, delay = 49, chat = "yell", male = "All Hail $n, slayer of Hakkar, and hero of Azeroth!" },
            { id = 10612, step = 4, speaker = 15076, delay = 49, chat = "yell", male = "The Blood God, the Soulflayer, has been defeated!  We are imperiled no longer!" },
        },
        [8277] = { -- Deadly Desert Venom
            { id = 10672, step = 1, speaker = 15190, delay = 1, chat = "say", male = "Wha... where am I?  So... weak.." },
        },
        [8278] = { -- Noggle's Last Hope
            { id = 10675, step = 1, speaker = 15190, delay = 2, chat = "say", male = "Yes!  I'm cured!  I'm cure... whoa, got up too fast!" },
        },
        [8282] = { -- Noggle's Lost Satchel
            { id = 10676, step = 1, speaker = 15190, delay = 2, chat = "say", male = "Thanks for finding my reagents!  *yawn*  That poison's made me... a bit tired..." },
        },
        [8412] = { -- Spirit Totem
            { id = 10865, step = 1, speaker = 6176, delay = 17, chat = "say", male = "I don't think it's strong enough." },
        },
        [8425] = { -- Voodoo Feathers
            { id = 10893, step = 1, speaker = 7572, delay = 4, chat = "say", male = "My fury is released!" },
        },
        [8484] = { -- The Brokering of Peace
            { id = 11308, step = 1, speaker = 2784, delay = 1, chat = "yell", male = "Let it be known that $n - Alliance $C - has earned the undying respect of Ironforge and the Alliance as a whole.  $GHe : She; has engaged in great diplomacy with Timbermaw Hold and performed valiant actions for them on our behalf.   $GHe : She; has gone above and beyond the call of duty.  Three cheers for $n - a true hero of the Alliance!" },
        },
        [8485] = { -- The Brokering of Peace
            { id = 11307, step = 1, speaker = 4949, delay = 1, chat = "yell", male = "Let it be known that $n - Horde $C - has earned the undying respect of the Warchief.   $GHe : She; has engaged in great diplomacy with Timbermaw Hold and performed valiant actions for them on our behalf.   $GHe : She; has gone above and beyond the call of duty.  Three cheers for $n - a true hero of the Horde!" },
        },
        [8791] = { -- The Fall of Ossirian
            { id = 11355, step = 1, speaker = 15181, delay = 1, chat = "yell", male = "Soldiers of Kalimdor! Heroes of Silithus! One among you has dealt a vicious blow to our mortal enemies! $n and $g his:her; allies have relieved the Ruins of Ahn'Qiraj of its merciless leader! Ossirian the Unscarred, scourge of Silithus, has finally been destroyed and his armies wholly dismantled!" },
        },
        [8905] = { -- An Earnest Proposition
            { id = 11881, step = 1, speaker = 16013, delay = 5, chat = "say", male = "You're never going to stop coming after me, are you?  Fine, but you won't take me down without a fight!" },
        },
        [8906] = { -- An Earnest Proposition
            { id = 11881, step = 1, speaker = 16013, delay = 5, chat = "say", male = "You're never going to stop coming after me, are you?  Fine, but you won't take me down without a fight!" },
        },
        [8907] = { -- An Earnest Proposition
            { id = 11881, step = 1, speaker = 16013, delay = 5, chat = "say", male = "You're never going to stop coming after me, are you?  Fine, but you won't take me down without a fight!" },
        },
        [8908] = { -- An Earnest Proposition
            { id = 11881, step = 1, speaker = 16013, delay = 5, chat = "say", male = "You're never going to stop coming after me, are you?  Fine, but you won't take me down without a fight!" },
        },
        [8909] = { -- An Earnest Proposition
            { id = 11881, step = 1, speaker = 16013, delay = 5, chat = "say", male = "You're never going to stop coming after me, are you?  Fine, but you won't take me down without a fight!" },
        },
        [8910] = { -- An Earnest Proposition
            { id = 11881, step = 1, speaker = 16013, delay = 5, chat = "say", male = "You're never going to stop coming after me, are you?  Fine, but you won't take me down without a fight!" },
        },
        [8911] = { -- An Earnest Proposition
            { id = 11881, step = 1, speaker = 16013, delay = 5, chat = "say", male = "You're never going to stop coming after me, are you?  Fine, but you won't take me down without a fight!" },
        },
        [8912] = { -- An Earnest Proposition
            { id = 11881, step = 1, speaker = 16013, delay = 5, chat = "say", male = "You're never going to stop coming after me, are you?  Fine, but you won't take me down without a fight!" },
        },
        [8913] = { -- An Earnest Proposition
            { id = 11895, step = 1, speaker = 16012, delay = 5, chat = "say", male = "Begone foul creatures!  Go back to the void your master shaped you from!" },
        },
        [8914] = { -- An Earnest Proposition
            { id = 11895, step = 1, speaker = 16012, delay = 5, chat = "say", male = "Begone foul creatures!  Go back to the void your master shaped you from!" },
        },
        [8915] = { -- An Earnest Proposition
            { id = 11895, step = 1, speaker = 16012, delay = 5, chat = "say", male = "Begone foul creatures!  Go back to the void your master shaped you from!" },
        },
        [8916] = { -- An Earnest Proposition
            { id = 11895, step = 1, speaker = 16012, delay = 5, chat = "say", male = "Begone foul creatures!  Go back to the void your master shaped you from!" },
        },
        [8917] = { -- An Earnest Proposition
            { id = 11895, step = 1, speaker = 16012, delay = 5, chat = "say", male = "Begone foul creatures!  Go back to the void your master shaped you from!" },
        },
        [8918] = { -- An Earnest Proposition
            { id = 11895, step = 1, speaker = 16012, delay = 5, chat = "say", male = "Begone foul creatures!  Go back to the void your master shaped you from!" },
        },
        [8919] = { -- An Earnest Proposition
            { id = 11895, step = 1, speaker = 16012, delay = 5, chat = "say", male = "Begone foul creatures!  Go back to the void your master shaped you from!" },
        },
        [8920] = { -- An Earnest Proposition
            { id = 11895, step = 1, speaker = 16012, delay = 5, chat = "say", male = "Begone foul creatures!  Go back to the void your master shaped you from!" },
        },
        [8984] = { -- The Source Revealed
            { id = 11838, step = 1, speaker = 16110, delay = 2, chat = "say", male = "Staffron..." },
            { id = 11836, step = 2, speaker = 16107, delay = 4, chat = "say", male = "Annalise? Is that you?" },
            { id = 11837, step = 3, speaker = 16110, delay = 8, chat = "say", male = "My dear Staffron, have you forgotten what it is to love? The love that we once shared?" },
            { id = 11839, step = 4, speaker = 16107, delay = 14, chat = "say", male = "Have I forgotten? Of course I have... I have forgotten about love, happiness... of life itself." },
            { id = 11840, step = 5, speaker = 16107, delay = 21, chat = "say", male = "But I do know this - love makes the heart and body weak. It can be exploited. Without your love, I have only my work, Annalise." },
            { id = 11841, step = 6, speaker = 16110, delay = 29, chat = "say", male = "But of course I love you, Staffron. And it pains me to see you suffer so." },
            { id = 11842, step = 7, speaker = 16110, delay = 36, chat = "say", male = "I pledge my love to you forever. Death cannot erase that, even as I am sure that you still remember your love for me." },
            { id = 11843, step = 8, speaker = 16110, delay = 43, chat = "say", male = "And if you do not, then I am truly lost." },
            { id = 11844, step = 9, speaker = 16107, delay = 48, chat = "say", male = "How could you love me, Annalise? Look at me. I am not the man you once knew." },
            { id = 11845, step = 10, speaker = 16107, delay = 56, chat = "say", male = "Annalise? Annalise! No, don't leave me!" },
            { id = 11846, step = 11, speaker = 16107, delay = 62, chat = "say", male = "Annalise... You're right. I-I can't do this. I must find another way." },
            { id = 11847, step = 12, speaker = 16107, delay = 68, chat = "say", male = "You there. You're welcome to take the contents of my cauldron. It was to be the second stage of my plan - amorous clothing." },
        },
        [9028] = { -- The Source Revealed
            { id = 11838, step = 1, speaker = 16110, delay = 2, chat = "say", male = "Staffron..." },
            { id = 11836, step = 2, speaker = 16107, delay = 4, chat = "say", male = "Annalise? Is that you?" },
            { id = 11837, step = 3, speaker = 16110, delay = 8, chat = "say", male = "My dear Staffron, have you forgotten what it is to love? The love that we once shared?" },
            { id = 11839, step = 4, speaker = 16107, delay = 14, chat = "say", male = "Have I forgotten? Of course I have... I have forgotten about love, happiness... of life itself." },
            { id = 11840, step = 5, speaker = 16107, delay = 21, chat = "say", male = "But I do know this - love makes the heart and body weak. It can be exploited. Without your love, I have only my work, Annalise." },
            { id = 11841, step = 6, speaker = 16110, delay = 29, chat = "say", male = "But of course I love you, Staffron. And it pains me to see you suffer so." },
            { id = 11842, step = 7, speaker = 16110, delay = 36, chat = "say", male = "I pledge my love to you forever. Death cannot erase that, even as I am sure that you still remember your love for me." },
            { id = 11843, step = 8, speaker = 16110, delay = 43, chat = "say", male = "And if you do not, then I am truly lost." },
            { id = 11844, step = 9, speaker = 16107, delay = 48, chat = "say", male = "How could you love me, Annalise? Look at me. I am not the man you once knew." },
            { id = 11845, step = 10, speaker = 16107, delay = 56, chat = "say", male = "Annalise? Annalise! No, don't leave me!" },
            { id = 11846, step = 11, speaker = 16107, delay = 62, chat = "say", male = "Annalise... You're right. I-I can't do this. I must find another way." },
            { id = 11847, step = 12, speaker = 16107, delay = 68, chat = "say", male = "You there. You're welcome to take the contents of my cauldron. It was to be the second stage of my plan - amorous clothing." },
        },
    },
    ["start"] = {
        [54] = { -- Report to Goldshire
            { id = 1242, step = 1, speaker = 197, delay = 2, chat = "say", male = "You are dismissed, $n." },
        },
        [155] = { -- The Defias Brotherhood
            { id = 9, step = 1, speaker = 467, delay = 0, chat = "say", male = "Follow me, $n. I'll take you to the Defias hideout. But you better protect me or I am as good as dead." },
        },
        [401] = { -- Wait for Sirra to Finish
            { id = 564, step = 1, speaker = 268, delay = 9, chat = "say", male = "$n, the translation is finished!" },
        },
        [409] = { -- Proving Allegiance
            { id = 1013, step = 1, speaker = 1497, delay = 0, chat = "say", male = "Take a Candle of Beckoning from this crate, $n." },
        },
        [434] = { -- The Attack!
            { id = 4593, step = 1, speaker = 8856, delay = 4, chat = "say", male = "By your command!" },
            { id = 3761, step = 2, speaker = 7766, delay = 7, chat = "say", male = "Wait here, $n. Spybot will make Lescovar come out as soon as possible. Be ready! Attack only after you've overheard their conversation." },
        },
        [452] = { -- Pyrewood Ambush
            { id = 542, step = 1, speaker = 2058, delay = 1, chat = "say", male = "Be ready, $n. I hear the council returning. Prepare to ambush!" },
        },
        [648] = { -- Rescue OOX-17/TN!
            { id = 3819, step = 1, speaker = 7784, delay = 1, chat = "say", male = "Emergency power activated!  Initializing ambulatory motor!  CLUCK!" },
        },
        [692] = { -- The Lost Fragments
            { id = 3004, step = 1, speaker = 2785, delay = 0, chat = "say", male = "Those thieving elementals are up the path, this way.  Good luck, $n." },
        },
        [723] = { -- Prospect of Faith
            { id = 957, step = 1, speaker = 2909, delay = 1, chat = "say", male = "Go with speed... <cough cough> Find... <cough> Ryedol..." },
        },
        [804] = { -- Sarkoth
            { id = 1341, step = 1, speaker = 3287, delay = 3, chat = "say", male = "Go swiftly, $n. My fate is in your hands." },
        },
        [836] = { -- Rescue OOX-09/HL!
            { id = 3794, step = 1, speaker = 7806, delay = 1, chat = "say", male = "Emergency power activated!  Initializing ambulatory motor!  CLUCK!" },
        },
        [854] = { -- Journey to the Crossroads
            { id = 1364, step = 1, speaker = 3418, delay = 0, chat = "say", male = "To reach The Crossroads, $n, follow the road east then north." },
        },
        [924] = { -- The Demon Seed
            { id = 1115, step = 1, speaker = 3521, delay = 1, chat = "say", male = "Take a stone from the table, $n.  You will need it for your quest." },
        },
        [947] = { -- Cave Mushrooms
            { id = 1211, step = 1, speaker = 3583, delay = 0, chat = "say", male = "Thank you, $n.  And luck to you." },
            { id = 1210, step = 2, speaker = 3583, delay = 3, chat = "say", male = "Cliffspring Falls lies along the mountains to the east and north." },
        },
        [993] = { -- A Lost Master
            { id = 1289, step = 1, speaker = 3693, delay = 4, chat = "say", male = "Go now, $n. Find Volcor... and remember, the magics protecting you will fail if you interact with anyone, save for talking." },
        },
        [1064] = { -- Forsaken Aid
            { id = 1419, step = 1, speaker = 4046, delay = 5, chat = "say", male = "Go, my servant.  Send word of Stonetalon to Apothecary Zamah." },
        },
        [1149] = { -- Test of Faith
            { id = 1589, step = 1, speaker = 2986, delay = 1, chat = "say", male = "Until we meet again, brave one." },
        },
        [1173] = { -- Challenge Overlord Mok'Morokk
            { id = 1515, step = 1, speaker = 4500, delay = 3, chat = "say", male = "Puny $r wanna fight Overlord Mok'Morokk? Me beat you! Me boss here!" },
        },
        [1221] = { -- Blueleaf Tubers
            { id = 1788, step = 1, speaker = 3446, delay = 0, chat = "say", male = "Hey $n!  Don't forget to grab a crate, a manual and a command stick!" },
        },
        [1273] = { -- Questioning Reethe
            { id = 1669, step = 1, speaker = 4983, delay = 1, chat = "say", male = "I noticed some fire on that island over there. A human, too. Let's go check it out, $n." },
        },
        [1363] = { -- Mazen's Behest
            { id = 1828, step = 1, speaker = 5386, delay = 1, chat = "say", male = "It wasn't my fault, Master Mazen!" },
            { id = 1829, step = 1, speaker = 5386, delay = 1, chat = "say", male = "It was a simple mistake. A wrong turn I tell you!" },
            { id = 1830, step = 1, speaker = 5386, delay = 1, chat = "say", male = "The swamp was horrible! I was so... so... scared!" },
            { id = 1831, step = 1, speaker = 5386, delay = 1, chat = "say", male = "I'm lucky to be alive!" },
        },
        [1476] = { -- Hearts of the Pure
            { id = 1988, step = 1, speaker = 5693, delay = 3, chat = "say", male = "This is Dalin Forgewright. He fled from Lordaeron when the plague struck, taking his love with him." },
            { id = 1992, step = 2, speaker = 5693, delay = 8, chat = "say", male = "When he came upon the refugees at the Greymane Wall, he felt it his duty to succor them, sending his woman on to Hillsbrad." },
            { id = 1989, step = 3, speaker = 5693, delay = 15, chat = "say", male = "And this is Comar Villard. Two weeks married, his wife was spirited away from the safety of Menethil Harbor." },
            { id = 1993, step = 4, speaker = 5693, delay = 19, chat = "say", male = "Five and five years, and he still searches for her, though she was no beauty, and there were many ladies that would take her place." },
            { id = 1990, step = 5, speaker = 5693, delay = 22, chat = "say", male = "Fools." },
        },
        [1680] = { -- Tormus Deepforge
            { id = 2302, step = 1, speaker = 6114, delay = 0, chat = "say", male = "Farewell, $n.  And remember, a warrior never shows his back to his foe!" },
        },
        [1699] = { -- The Rethban Gauntlet
            { id = 2261, step = 1, speaker = 6166, delay = 0, chat = "say", male = "Good luck, $n!" },
        },
        [1713] = { -- The Summoning
            { id = 2383, step = 1, speaker = 6176, delay = 2, chat = "say", male = "Follow, $n.  I will soon begin the summoning..." },
        },
        [1738] = { -- Heartswood
            { id = 2310, step = 1, speaker = 6244, delay = 1, chat = "say", male = "A thousand years ago, the immortal elves, demigods of the forest and dragons fought against the Legion on the slopes of Hyjal." },
            { id = 2311, step = 2, speaker = 6244, delay = 8, chat = "say", male = "Anathera and Latherion fought back to back where the battle was thickest. Two lovers determined to survive the war together." },
            { id = 2312, step = 3, speaker = 6244, delay = 12, chat = "say", male = "But it was not to be. As their foes pressed close, Anathera's armor was pierced by a demon's tainted blade. In the thick of battle, there would be nothing to save her." },
            { id = 2313, step = 4, speaker = 6246, delay = 15, chat = "say", male = "Anathera!" },
            { id = 2314, step = 5, speaker = 6244, delay = 20, chat = "say", male = "Ignoring the battle that raged about him, Latherion dropped his guard to cradle his love in her dying moments. But the demons gave him no quarter, and quickly laid him low." },
            { id = 2315, step = 6, speaker = 6246, delay = 24, chat = "say", male = "Anathera... I cannot bear to face the rest of eternity without you by my side... If you are taken from me, then let this be the day I also return to the earth..." },
            { id = 2316, step = 7, speaker = 6245, delay = 26, chat = "say", male = "So this... this is how it ends, my love..." },
            { id = 2317, step = 8, speaker = 6244, delay = 30, chat = "say", male = "Where the two lovers fell, a tree would bloom. The elves call it the heartswood. It will surely serve your ends." },
        },
        [1784] = { -- The Tome of Divinity
            { id = 2351, step = 1, speaker = 6177, delay = 0, chat = "say", male = "Good luck, $n. And remember, find Muiredon once you've accomplished the task." },
        },
        [1787] = { -- The Tome of Divinity
            { id = 2353, step = 1, speaker = 6172, delay = 0, chat = "say", male = "Good luck to you, $n. And don't forget... get that script before finding Gazin." },
        },
        [1795] = { -- The Binding
            { id = 2370, step = 1, speaker = 6251, delay = 1, chat = "say", male = "I hope you're ready, $n. Follow me." },
        },
        [1806] = { -- The Test of Righteousness
            { id = 2501, step = 1, speaker = 6181, delay = 4, chat = "say", male = "Let's get to work, $n!" },
            { id = 2521, step = 2, speaker = 6181, delay = 19, chat = "say", male = "I thank the Light for this blessing. May it be used for justice and to defend all good creatures." },
            { id = 2504, step = 3, speaker = 6181, delay = 27, chat = "say", male = "Here you are, $n." },
        },
        [1920] = { -- Investigate the Blue Recluse
            { id = 2681, step = 1, speaker = 5497, delay = 1, chat = "say", male = "Here, $n.  Take a chest of containment coffers and a cantation of manifestation.  You will need them for your mission." },
        },
        [1952] = { -- Mage's Wand
            { id = 2708, step = 1, speaker = 6546, delay = 1, chat = "say", male = "Stand back, and ... hold your breath.  I haven't done this in a while." },
            { id = 2709, step = 2, speaker = 6546, delay = 9, chat = "say", male = "It worked!  Amazing!  I guess I haven't lost my touch..." },
        },
        [1955] = { -- The Exorcism
            { id = 2629, step = 1, speaker = 6546, delay = 0, chat = "say", male = "Gird yourself, $n, for the demon in this orb is a fel beast." },
        },
        [1957] = { -- Mana Surges
            { id = 2592, step = 1, speaker = 6546, delay = 1, chat = "say", male = "Prepare yourself, $n.  I go to open the rift..." },
        },
        [1960] = { -- Investigate the Alchemist Shop
            { id = 2682, step = 1, speaker = 4568, delay = 1, chat = "say", male = "Take a chest of containment coffers and a cantation of manifestation, $n.  You will need them for your mission." },
        },
        [2282] = { -- Alther's Mill
            { id = 3562, step = 1, speaker = 6966, delay = 1, chat = "whisper", male = "Oh! I almost forgot! I slipped you a set of thieven' tools. You'll need those where you're going." },
        },
        [2359] = { -- Klaven's Tower
            { id = 3264, step = 1, speaker = 7024, delay = 0, chat = "say", male = "Be sure to read over the notes in my journal, $n. You will find them to be invaluable in overcoming the tower's defenses." },
        },
        [2381] = { -- Plundering the Plunderers
            { id = 3171, step = 1, speaker = 7161, delay = 0, chat = "say", male = "Make sure to visit the Gizmotronic Apparatus to grab a lockpick and an E.C.A.C. You will definitely need both to complete your mission!" },
        },
        [2460] = { -- The Shattered Salute
            { id = 3278, step = 1, speaker = 3401, delay = 1, chat = "say", male = "$n, pay very close attention to what I do and follow my instructions precisely. To not heed my words is to sign your own death warrant, as Taskmaster Fizzule is VERY well versed in the ways of the warrior and the assassin." },
            { id = 3279, step = 2, speaker = 3401, delay = 8, chat = "say", male = "After you get his attention - and you can be certain that if he sees you near the tower, you'll have his undue attention - face him and perform the Shattered /Salute. Let me demonstrate...." },
            { id = 3281, step = 3, speaker = 3401, delay = 25, chat = "say", male = "Did you see what I did? If you are unsure of the technique used in presenting the /salute, practice on me. If you correctly execute the Shattered /Salute, I will give you the proper response." },
        },
        [2480] = { -- Hinott's Assistance
            { id = 3326, step = 1, speaker = 2391, delay = 36, chat = "say", male = "Whoops!" },
        },
        [2608] = { -- The Touch of Zanzil
            { id = 3567, step = 1, speaker = 7207, delay = 0, chat = "say", male = "Just /lay down anywhere, $n. I promise, this won't hurt a bit!" },
        },
        [2662] = { -- Noggenfogger Elixir
            { id = 4548, step = 1, speaker = 7564, delay = 0, chat = "say", male = "I'm going to carefully mix this - oops! ...Well, I spilled a little, but it's ready!" },
        },
        [2765] = { -- Expert Blacksmith!
            { id = 3828, step = 1, speaker = 7802, delay = 0, chat = "say", male = "Stand by, $n! To craft a reward of such exquisite quality takes time." },
            { id = 3825, step = 2, speaker = 7802, delay = 33, chat = "say", male = "I am almost done, $n. Just a few more adjustments!" },
            { id = 3826, step = 3, speaker = 7802, delay = 41, chat = "say", male = "DONE!" },
        },
        [2767] = { -- Rescue OOX-22/FE!
            { id = 3819, step = 1, speaker = 7807, delay = 1, chat = "say", male = "Emergency power activated!  Initializing ambulatory motor!  CLUCK!" },
        },
        [2841] = { -- Rig Wars
            { id = 3903, step = 1, speaker = 3413, delay = 1, chat = "whisper", male = "Come and have a talk with me if you're going to go to Gnomeregan, $n!" },
        },
        [2843] = { -- Gnomer-gooooone!
            { id = 3904, step = 1, speaker = 7853, delay = 1, chat = "say", male = "Give me a moment while I calibrate the transponder to your height and weight specifications, $n." },
            { id = 3905, step = 2, speaker = 7853, delay = 7, chat = "say", male = "Alright, $n, your transponder is ready!" },
        },
        [2992] = { -- The Divination
            { id = 4126, step = 1, speaker = 8022, delay = 0, chat = "say", male = "Make no sound during the ritual.  One misstep could spell our doom..." },
            { id = 4128, step = 2, speaker = 8022, delay = 8, chat = "say", male = "There.  It is done." },
        },
        [3129] = { -- Weapons of Spirit
            { id = 4176, step = 1, speaker = 8115, delay = 28, chat = "say", male = "I have completed the weapons, $n." },
        },
        [3321] = { -- Did You Lose This?
            { id = 4365, step = 1, speaker = 7804, delay = 1, chat = "yell", male = "Hear ye, denizens of Tanaris! Let it be known that $n is an exalted member of the Mithril Order. A blacksmith of honor, dedication, and infinite patience. Three cheers for $n!" },
        },
        [3453] = { -- The Torch of Retribution
            { id = 4448, step = 1, speaker = 8479, delay = 16, chat = "say", male = "Be patient, $n. The torch is almost complete." },
            { id = 4450, step = 2, speaker = 8479, delay = 27, chat = "say", male = "It is done..." },
        },
        [3602] = { -- Azsharite
            { id = 4576, step = 1, speaker = 7783, delay = 0, chat = "whisper", male = "You will need to open the Felhound Tracker Kit and read the instruction manual. Summon the beast when you are near the peninsula of cliff giants, south of here." },
        },
        [3625] = { -- Enchanted Azsharite Fel Weaponry
            { id = 4542, step = 1, speaker = 7802, delay = 5, chat = "say", male = "Your fel weapon is ready, $n." },
        },
        [4021] = { -- Counterattack!
            { id = 4926, step = 1, speaker = 3389, delay = 0, chat = "say", male = "Beware, $n!  Look to the west!" },
        },
        [4321] = { -- Making Sense of It
            { id = 5287, step = 1, speaker = 9117, delay = 2, chat = "say", male = "Now, let's see... If I am correct, then... Hmmm..." },
            { id = 5288, step = 2, speaker = 9117, delay = 6, chat = "say", male = "Blue plus red... I predict..." },
            { id = 5289, step = 3, speaker = 9117, delay = 9, chat = "say", male = "$n, that's it! I have finally figured it out!" },
        },
        [4442] = { -- Purified!
            { id = 8366, step = 1, speaker = 9116, delay = 1, chat = "say", male = "May this evil aura be banished from this artifact!" },
            { id = 8367, step = 2, speaker = 9116, delay = 8, chat = "say", male = "I can feel the presence of evil leaving..." },
        },
        [4513] = { -- A Little Slime Goes a Long Way
            { id = 5449, step = 1, speaker = 9616, delay = 1, chat = "say", male = "There must be someplace on Azeroth that we can find oozes uncorrupted by the Scourge or anything else. But where?!" },
        },
        [4901] = { -- Guardians of the Altar
            { id = 7365, step = 1, speaker = 10300, delay = 1, chat = "say", male = "Remember, I need your help to properly channel. I will ask you to aid me several times on our path, so please be ready." },
        },
        [4961] = { -- Cleansing of the Orb of Orahil
            { id = 2629, step = 1, speaker = 6546, delay = 0, chat = "say", male = "Gird yourself, $n, for the demon in this orb is a fel beast." },
        },
        [4964] = { -- The Completed Orb of Dar'Orahil
            { id = 2663, step = 1, speaker = 6266, delay = 1, chat = "say", male = "Ok, let's get this orb made..." },
            { id = 2664, step = 2, speaker = 6266, delay = 8, chat = "say", male = "All right.  It's made!" },
        },
        [4966] = { -- Protect Kanati Greycloud
            { id = 6149, step = 1, speaker = 10638, delay = 2, chat = "say", male = "Here they come! Defend yourselves!" },
        },
        [4975] = { -- The Completed Orb of Noh'Orahil
            { id = 2663, step = 1, speaker = 6266, delay = 1, chat = "say", male = "Ok, let's get this orb made..." },
            { id = 2664, step = 2, speaker = 6266, delay = 8, chat = "say", male = "All right.  It's made!" },
        },
        [5252] = { -- Remorseful Highborne
            { id = 6505, step = 1, speaker = 10684, delay = 0, chat = "yell", male = "Highborne spirits! Be at peace! The Crystal of Zin-Malor is whole once again!" },
            { id = 6506, step = 1, speaker = 10684, delay = 0, chat = "yell", male = "Cursed spirits! Let go of the past! The Crystal of Zin-Malor no longer binds you!" },
            { id = 6507, step = 1, speaker = 10684, delay = 0, chat = "yell", male = "Spirits of the Highborne! You may now rest! The curse of the crystal releases you!" },
        },
        [5713] = { -- One Shot. One Kill.
            { id = 7200, step = 1, speaker = 11711, delay = 1, chat = "say", male = "Wait... did you hear that? Something approaches from the west!" },
            { id = 7199, step = 2, speaker = 11711, delay = 120, chat = "say", male = "I've run out of arrows! I'm afraid if any more come you will need to take them on by yourself my friend." },
        },
        [6523] = { -- Protect Kaya
            { id = 8327, step = 1, speaker = 11856, delay = 1, chat = "say", male = "Let's go before they find out I'm free!" },
        },
        [6641] = { -- Vorsha the Lasher
            { id = 8566, step = 1, speaker = 12717, delay = 3, chat = "say", male = "Are you sure that you are ready? If we do not have a group of your allies to aid us, we will surely fail." },
            { id = 8555, step = 2, speaker = 12717, delay = 7, chat = "say", male = "This will be a tough fight, $n. Follow me closely!" },
        },
        [7029] = { -- Vyletongue Corruption
            { id = 8923, step = 1, speaker = 11823, delay = 0, chat = "say", male = "$n, please take a look at the sample of the Vylestem vine that I took from the caverns, so that you know what to look for..." },
        },
        [7041] = { -- Vyletongue Corruption
            { id = 8923, step = 1, speaker = 11715, delay = 1, chat = "say", male = "$n, please take a look at the sample of the Vylestem vine that I took from the caverns, so that you know what to look for..." },
        },
    },
}
