setfenv(1, SpokenEnv)

-- Interface strings, keyed for the locale overlays in Locale/.
-- English is the fallback: a locale file assigns only the keys it translates.
L = {
    PLAY = "Play",
    OPT_MINIMAL_PLAYER = "Minimal Classic player",
    OPT_MINIMAL_PLAYER_TIP = "Compact native-style portrait and progress bar. Click the quest title to skip it, or the plus button for the queue; right-click for playback and source actions. Turn off to restore the original player.",
    MIN_QUEUE_HINT = "%1$d queued. Click to show or hide the queue.",
    MIN_MENU_HINT = "Right-click for playback options. Drag the speaker name to move.",
    MIN_SKIP = "Skip line",
    MIN_STOP_ALL = "Stop all",
    MIN_RESTART = "Play from beginning",
    MIN_SCROLL_QUEUE = "%1$d-%2$d of %3$d  (scroll)",
    PAUSE = "Pause",
    PAUSE_TOOLTIP = "Pause stops the clip; play starts it again from the beginning. The game cannot resume a sound part-way through.",
    STOP = "Stop",
    SETTINGS = "Settings",
    PLAY_PAUSE = "Play/Pause",
    QUEUE_TITLE = "Up next",
    -- The settings heading for the window above, which "Up next" -- the window's own
    -- title, on its tooltip -- did not describe.
    OPT_WINDOW_TITLE = "Player window",
    QUEUE_DRAG_HINT = "Drag to move. The position can be locked in settings.",
    QUEUE_REMOVE_TOOLTIP = "Click to take this out of the queue.",
    MENU_LEFT = "|cff66bbffLeft-click|r open the menu",
    MENU_RIGHT = "|cff66bbffRight-click|r open settings",
    MENU_MIDDLE = "|cff66bbffMiddle-click|r play/pause",
    OPT_LOCK_FRAME = "Lock the player",
    OPT_LOCK_FRAME_TIP = "Prevent the player from being moved or resized.",
    OPT_HIDE_PORTRAIT = "Hide the portrait",
    OPT_HIDE_PORTRAIT_TIP = "Show the queue without the speaker's portrait. Useful alongside addons that replace the dialog window.",
    OPT_HIDE_FRAME = "Hide the player entirely",
    OPT_HIDE_FRAME_TIP = "Play everything without ever showing the window.",
    OPT_HIDE_ACTION = "Hide the %1$s button",
    OPT_HIDE_ACTION_TIP = "Takes it off the player. What it does is reachable elsewhere.",
    OPT_SCALE = "Player scale",
    OPT_CONTRIBUTE_TITLE = "Contributions",
    OPT_HIDE_CONTRIBUTE = "Hide the Contribute buttons",
    OPT_HIDE_CONTRIBUTE_TIP = "Stop offering to send the game's text for quests, books and places that have no voice yet.",
    OPT_GATHER = "Gather missing lines in the background",
    OPT_GATHER_TIP = "Keep every quest, conversation and page Spoken has no voice for, so you can send them all at once instead of one Contribute at a time.",
    OPT_GATHER_SHARE = "How to send them",
    OPT_GATHER_CLEAR = "Clear gathered lines",
    OPT_GATHER_CLEAR_TIP = "Forget everything gathered so far. Do this after you have sent the file.",
    CONTRIBUTE_INTRO = "Spoken has no voice for this yet, and the game's own text is how it gets one.\n\nYou can send just this line now, or let Spoken quietly keep every line it is missing while you play, and send them all at once whenever you like.\n\nNothing leaves your game until you upload it yourself, and you can stop gathering at any time in the Spoken Player settings.",
    CONTRIBUTE_JUST_THIS = "Send just this line",
    CONTRIBUTE_GATHER = "Gather as I play",
    GATHER_INSTRUCTIONS = "Gathering is on: %1$d line(s) kept so far. Play as usual.\n\nTo send them:\n1. Log out, or type /reload, so the game writes its files.\n2. Open spoken.rusty.one/contribute and choose Upload a file.\n3. Pick this file:\nWorld of Warcraft\\%2$s\\WTF\\Account\\<your account>\\SavedVariables\\SpokenContributions.lua\n\nThen clear the gathered lines in the Spoken Player settings. /spoken share shows this again.",
    OPT_RESET = "Reset position",
    OPT_AUDIO_TITLE = "Audio",
    OPT_CHANNEL = "Sound channel",
    OPT_CHANNEL_TIP = "Which of the game's sound channels every Spoken addon speaks on. Each follows its own volume slider in the game's sound options.",
    OPT_CHANNEL_MASTER = "Master",
    OPT_CHANNEL_SFX = "SFX",
    OPT_CHANNEL_MUSIC = "Music",
    OPT_CHANNEL_AMBIENCE = "Ambience",
    OPT_CHANNEL_DIALOG = "Dialog",
    OPT_MUTE_DIALOGUE = "Silence the game's own dialogue while speaking",
    OPT_MUTE_DIALOGUE_TIP = "Mute the Dialog channel while a line is being read, so an NPC's own voice does not talk over it. Restored when the queue empties.",
    OPT_MUTE_DIALOGUE_TIP_VANILLA = "Cut off an NPC's greeting voiceline when a line starts being read.",
    OPT_MUSIC_CHANNEL = "Play through the music channel",
    OPT_MUSIC_CHANNEL_TIP = "This client cannot stop a sound once it has started, so speech is routed through the music channel, which can be stopped. Turn this off and a line cannot be paused or skipped once it starts.",
    OPT_MUSIC_VOLUME = "Speech volume",
    OPT_MUSIC_FADE = "Fade the music out over",
    OPT_HD_MODELS = "HD model patch installed",
    OPT_HD_MODELS_TIP = "Use the animation timings of the high-definition character models, if you have patched them in. Portraits will mouth their lines out of step otherwise.",
    OPT_MINIMAP_TITLE = "Minimap",
    OPT_ADDONS_TITLE = "Spoken addons",
    OPT_MINIMAP_SHOW = "Show the minimap button",
    OPT_MINIMAP_LOCK = "Lock the minimap button",
    OPT_NO_SETTINGS_API = "open Game Menu -> Options -> AddOns -> Spoken Player, or type /spoken options",
    OPT_COPY_HINT_LINK = "Copy this and open it in your browser:",
    OPT_COPY_HINT_PASTE = "Press Ctrl+C, then paste it at:",
    -- The client's "blocked from an action only available to the Blizzard UI" popup, explained.
    TAINT_NOTICE = "Spoken: the game blocked %1$s from calling %2$s. Type /spoken taint to copy a report for the bug tracker.",
    TAINT_COPY_HINT = "Press Ctrl+C, then paste it into the bug report:",
    TAINT_LOG_ON = "Spoken: the game's taint log is on. Reproduce the problem, exit the game, then attach Logs\\taint.log from your game folder to the bug report. /spoken taint off turns it off again.",
    TAINT_LOG_OFF = "Spoken: the game's taint log is off.",
}
