/**
 * Finding lines.
 *
 * Results are a flat, paged list of lines rather than a tree of NPCs, because the corpus is
 * 17,507 lines and the useful question is often "which line says this?", not "what does this
 * NPC say?". A flat list is also the only shape that can be paged: an NPC's lines are an
 * indivisible unit, so grouping first puts a floor under how much a page can cost.
 *
 * The npc and quest filters, and the voice filter, still mean what select_lines
 * (tts_cli/select.py) means by them, so "npc 240" reads the same on the CLI and in the
 * browser; search.test.ts is what keeps the two honest. Text, race, gender, source and
 * entity-type filtering are web-only and have no CLI counterpart to stay in step with.
 */
import type { Corpus, CorpusLine } from "./corpus";
import { npcKey } from "./corpus";
import { audioRelPath } from "./audio";
import { hasNarration, restoresOnlyNarration } from "./generation/narration";
import type { NpcType, Source } from "./line-fields";
import type { LineIgnore } from "./quests/ignores";
import type { LineOverride } from "./quests/override";
import { isVoiceable } from "./text-gate";

/** Which field the free-text query is matched against. */
export type Filter = "any" | "npc" | "quest" | "text";

/**
 * Everything that narrows the corpus, with no bearing on which slice of the result is asked
 * for. Split out from paging because the batch endpoint needs the whole match set.
 */
export type LineFilters = {
  q?: string;
  filter?: Filter;
  missingOnly?: boolean;
  race?: string;
  gender?: string;
  flavor?: string;
  voice?: string;
  source?: Source;
  npcType?: NpcType;
  /** Only lines carrying a capitalised <stage direction>, which a narrator reads. */
  narration?: boolean;
  /**
   * Whether to include progress text, which is hidden unless asked for.
   *
   * 3,093 lines - 17.7% of the corpus - that no code path will ever voice: the generator
   * refuses them before the request (tts_cli/tts_utils.py) and so does regeneration
   * (lib/text-gate.ts). Showing them by default pads every search with results nobody can
   * act on, so absent means hidden and this is how you ask for them back.
   *
   * Widening rather than narrowing, which is why activeFilterCount ignores it.
   */
  includeProgress?: boolean;
  /**
   * One line by its id, which is how a report reaches the corpus.
   *
   * Not unique, and the filter does not pretend otherwise: a gossip lineId is a hash of the
   * text, so every NPC of that race and gender saying it carries the same one. A report
   * about such a line is a report about all of them, and the triager wants to see the set.
   */
  line?: string;
  /** Lines whose spoken text has been rewritten by hand. */
  overridden?: boolean;
  /**
   * Show only the lines somebody decided never to voice, which are hidden by default.
   *
   * The war-effort tallies and Blizzard's test quest: 36 lines that will never have audio,
   * and which pad every search for a gap with results nobody can act on. Hidden rather than
   * deleted because the decision is reversible and the reason is worth reading, so this is
   * how you go and read it.
   */
  ignored?: boolean;
  /** Lines whose audio was made from text that has since changed. */
  outdated?: boolean;
  /**
   * Lines whose audio was made before a pronunciation it speaks was changed.
   *
   * Not a narrower `outdated`, and not implied by it: a lexicon edit moves no text, so the
   * two select disjoint problems with the same audio and either can be true alone.
   */
  dirty?: boolean;
  /**
   * 'open' selects lines carrying at least one unresolved report. A value rather than a
   * boolean, and `fb` in the URL, to match the zones and books filters it mirrors.
   */
  reports?: "open";
  /**
   * Bounds on when the live take was generated, as "YYYY-MM-DD". Both include the whole of
   * the day they name, which is what picking a day off a calendar means.
   *
   * A file the app has never written has no date at all - the corpus was generated by the
   * CLI, which records nothing - and those count as generated infinitely long ago. So they
   * are always in a "before", never in an "after". That keeps "before" usable as "what have
   * I not touched since?", which is the question worth asking while 9,450 of 9,456 files
   * have no record.
   */
  generatedBefore?: string;
  generatedAfter?: string;
};

/** Midnight local at the start of a "YYYY-MM-DD", or null when it is not one. */
export function dayStart(day: string): number | null {
  if (!/^\d{4}-\d{2}-\d{2}$/.test(day)) return null;
  const at = new Date(`${day}T00:00:00`);
  return Number.isNaN(at.getTime()) ? null : at.getTime();
}

const DAY_MS = 24 * 60 * 60 * 1000;

/**
 * What the corpus alone cannot say about a line: what is wrong with it, and what someone has
 * decided it should say instead.
 *
 * Passed in rather than read here, because both come from Postgres and this module is a pure
 * function of the corpus - which is what lets search.test.ts hold two corpora and no database.
 * Defaulted to empty so a caller that has neither still gets a search.
 */
export type SearchContext = {
  overrides: Map<string, LineOverride>;
  /** When each file's live take was generated, epoch ms. Absent means no record. */
  generatedAt?: Map<string, number>;
  /**
   * Files whose live take was made from different text than would be sent today. Absent
   * means nobody asked, not that every take is current.
   */
  stale?: Set<string>;
  /**
   * Files whose live take predates a change to a pronunciation it speaks, with nobody having
   * said since that it is fine. Absent means nobody asked, as with `stale`.
   */
  dirty?: Set<string>;
  /**
   * Lines nobody will voice, with the reason. Absent means the database could not be
   * reached, which shows them rather than hiding them: an outage should not silently narrow
   * the corpus, and a visible extra row is the safer way to be wrong.
   */
  ignores?: Map<string, LineIgnore>;
  /**
   * lineId -> how many reports about it are still open. The count only; the bodies are
   * behind the triage role on /reports, as they are for the other two sections.
   */
  reports?: Map<string, number>;
  /** file -> which take is live and how many there are. Public, like the other two rows'. */
  takes?: Map<string, { version: number; takes: number }>;
};

export const NO_CONTEXT: SearchContext = { overrides: new Map() };

export type SearchOptions = LineFilters & {
  offset?: number;
  limit?: number;
};

export type ResultLine = CorpusLine & {
  /** Unique row identity. See rowKeys - lineId is not unique, and neither is much else. */
  key: string;
  hasAudio: boolean;
  audioPath: string;
  /** How many reports about this line are still open. Zero when nobody has said anything. */
  reportsOpen: number;
  /**
   * The live take of this line's file, and how many takes it has. Null when none is
   * recorded, which means the line has never been generated. Shaped like the zones and
   * books rows' `take` for the same reason the Audio column is shaped like theirs.
   */
  take: { version: number; takes: number } | null;
  /** The live take was cut from text that has since changed. */
  stale: boolean;
  /**
   * The live take was cut before a pronunciation it speaks was changed, and nobody has
   * said since that it is fine. Orthogonal to `stale`: a lexicon edit moves no text.
   */
  dirty: boolean;
  /** The rewritten spoken text, or null. `text` stays what the corpus says. */
  override: string | null;
  /**
   * Whether this line would be voiced *now*, which `generatable` cannot answer: that flag was
   * computed in Python from text nobody could edit yet, so an override that strips a stage
   * direction makes a line voiceable without moving it.
   */
  voiceable: boolean;
  /** Carries a capitalised <stage direction>, so it regenerates as two-voice dialogue. */
  narration: boolean;
  /**
   * The override only puts stage directions back and changed no words, so this is not a
   * rewrite anyone should be asked to review.
   */
  narrationRestored: boolean;
  /** Why this line will never be voiced, or null. Set only when the row is one of them. */
  ignored: string | null;
};

export type SearchResult = {
  /** This page only. */
  lines: ResultLine[];
  /** Matching lines across every page. */
  total: number;
  /** Distinct NPCs across every page, which no count of `lines` can recover. */
  npcCount: number;
  offset: number;
  limit: number;
};

export const PAGE_SIZE = 50;

/**
 * One unit of work in a batch regeneration.
 *
 * Deliberately not a ResultLine: a batch is the whole match set, which can be every line in
 * the corpus, and sending `text` and `originalText` for 17,507 of them to decide what a
 * button should cost is megabytes spent on two numbers and a label.
 */
export type BatchLine = {
  lineId: string;
  audioPath: string;
  npcName: string;
  voice: string;
  /** text.length, which is all the cost estimate needs. */
  characters: number;
  /** Enough of the line to recognise it in the progress readout. */
  preview: string;
};

/**
 * The lines a batch would actually generate.
 *
 * Deduplicated by audio file, because 1,076 files in the corpus are spoken by more than one
 * NPC and generating a shared file twice would pay for it twice and leave the second take
 * live. Lines the generator never voices are dropped here rather than failed one by one.
 */
export function batchJobs(
  lines: CorpusLine[],
  overrides: Map<string, LineOverride> = NO_CONTEXT.overrides,
): BatchLine[] {
  const byFile = new Map<string, BatchLine>();
  for (const line of lines) {
    const audioPath = audioRelPath(line);
    // The effective text, so the estimate prices what will actually be sent and a rescued
    // line is not quietly dropped from the batch that was quoted for it.
    const text = overrides.get(audioPath)?.text ?? line.text;
    if (!isVoiceable(line, text)) continue;
    if (byFile.has(audioPath)) continue;
    byFile.set(audioPath, {
      lineId: line.lineId,
      audioPath,
      npcName: line.npcName,
      voice: line.voice,
      characters: text.length,
      preview: text.slice(0, 80),
    });
  }
  return [...byFile.values()];
}

const keyCache = new WeakMap<Corpus, Map<CorpusLine, string>>();

/**
 * A unique key per corpus line, for React and for addressing a row in the DOM.
 *
 * Position in the corpus, because nothing carried by a line is unique. lineId is not: a
 * gossip lineId is a hash of the text, so every NPC of that race and gender saying it shares
 * one. Adding the NPC and the quest is not enough either - 141 quest lines in the corpus
 * share an NPC, a quest id, a source *and* an mp3 with another line whose text differs, and
 * those are indistinguishable by any field at all.
 *
 * Grouping by NPC used to hide all of this. A flat list cannot.
 *
 * Keyed off the corpus object rather than a module global so a test can hold two.
 */
export function rowKeys(corpus: Corpus): Map<CorpusLine, string> {
  let keys = keyCache.get(corpus);
  if (!keys) {
    keys = new Map(corpus.lines.map((line, index) => [line, `${line.lineId}#${index}`]));
    keyCache.set(corpus, keys);
  }
  return keys;
}

function matches(line: CorpusLine, q: string, filter: Filter): boolean {
  const needle = q.toLowerCase();
  const textHit = line.text.toLowerCase().includes(needle);
  if (filter === "text") return textHit;

  // A bare number is an id lookup, not a substring: this is what the CLI means by it, and
  // "240" finding every line that mentions 240 gold would bury the NPC you asked for.
  const asNumber = /^\d+$/.test(q) ? Number(q) : null;
  if (asNumber !== null) {
    const npcHit = line.npcId === asNumber;
    const questHit = line.questId === asNumber;
    if (filter === "npc") return npcHit;
    if (filter === "quest") return questHit;
    return npcHit || questHit;
  }

  const npcHit = line.npcName.toLowerCase().includes(needle);
  const questHit = (line.questTitle ?? "").toLowerCase().includes(needle);
  if (filter === "npc") return npcHit;
  if (filter === "quest") return questHit;
  return npcHit || questHit || textHit;
}

/**
 * A gap: a line the generator would voice, with no live take.
 *
 * Same definition as missing_lines (tts_cli/store.py) - lines the generator never voices
 * (progress text, unresolved template tokens) are expected absences, not gaps.
 */
export function isGap(
  line: CorpusLine,
  store: Set<string>,
  overrides: Map<string, LineOverride> = NO_CONTEXT.overrides,
): boolean {
  const audioPath = audioRelPath(line);
  const text = overrides.get(audioPath)?.text ?? line.text;
  return isVoiceable(line, text) && !store.has(audioPath);
}

/**
 * Display order.
 *
 * Deterministic first of all, because paging a list whose order can shift would drop and
 * repeat rows between pages. Within that, an NPC's lines stay adjacent and their quests stay
 * together, so the flat list still reads like a conversation rather than a shuffled index.
 * Gossip sorts after every quest, where the old gossip group also sat.
 */
function order(a: CorpusLine, b: CorpusLine): number {
  return (
    a.npcName.localeCompare(b.npcName) ||
    npcKey(a).localeCompare(npcKey(b)) ||
    // U+FFFF, so a null quest title (gossip) sorts after any real one.
    (a.questTitle ?? "￿").localeCompare(b.questTitle ?? "￿") ||
    a.lineId.localeCompare(b.lineId)
  );
}

/**
 * Every line the filters admit, unpaged and in display order.
 *
 * Exported because regenerating "everything matching" acts on the whole set, not the page
 * someone happens to be looking at.
 */
export function matchingLines(
  corpus: Corpus,
  store: Set<string>,
  {
    q = "",
    filter = "any",
    missingOnly = false,
    race,
    gender,
    flavor,
    voice,
    source,
    npcType,
    includeProgress = false,
    narration = false,
    line: lineId,
    overridden,
    outdated = false,
    dirty = false,
    ignored = false,
    reports,
    generatedBefore,
    generatedAfter,
  }: LineFilters = {},
  {
    overrides,
    generatedAt,
    stale,
    dirty: dirtyOf,
    ignores,
    reports: reportsOf,
  }: SearchContext = NO_CONTEXT,
): CorpusLine[] {
  const query = q.trim();

  let lines = corpus.lines;
  // First, and whichever way round: a line nobody will voice is not an answer to any other
  // question either, so every count and every "regenerate everything matching" is computed
  // over a corpus without them unless they are what was asked for.
  if (ignores?.size) {
    lines = ignored
      ? lines.filter((line) => ignores.has(line.lineId))
      : lines.filter((line) => !ignores.has(line.lineId));
  }
  if (query) lines = lines.filter((line) => matches(line, query, filter));
  if (missingOnly) lines = lines.filter((line) => isGap(line, store, overrides));
  if (race) lines = lines.filter((line) => line.race === race);
  if (gender) lines = lines.filter((line) => line.gender === gender);
  if (flavor) lines = lines.filter((line) => line.flavor === flavor);
  if (voice) lines = lines.filter((line) => line.voice === voice);
  if (source) lines = lines.filter((line) => line.source === source);
  // After the source filter and not before it, so asking for progress explicitly still works:
  // `source=progress` alone would otherwise return nothing at all.
  if (!includeProgress && source !== "progress") {
    lines = lines.filter((line) => line.source !== "progress");
  }
  if (npcType) lines = lines.filter((line) => line.npcType === npcType);
  // The *effective* text, matching the chip on the row and the text regeneration will send.
  // Reading line.text instead hid every line whose direction was restored by an override -
  // which is 314 of them, and the ones most worth finding.
  if (narration) {
    lines = lines.filter((line) =>
      hasNarration(overrides.get(audioRelPath(line))?.text ?? line.text),
    );
  }
  // An id the corpus no longer carries matches nothing rather than everything, because a
  // report about a dropped line must not read as "here it is".
  if (lineId) lines = lines.filter((line) => line.lineId === lineId);
  // Absent `stale` means nobody asked for it, so nothing matches rather than everything: the
  // honest answer to "which audio is out of date?" without the data is none, not all.
  if (outdated) lines = lines.filter((line) => stale?.has(audioRelPath(line)) ?? false);
  // Absent `dirty` means nobody asked, so nothing matches rather than everything - the
  // argument the line above makes, for the same reason.
  if (dirty) lines = lines.filter((line) => dirtyOf?.has(audioRelPath(line)) ?? false);
  // Absent counts mean the database was not reached, and "which lines are reported?" has
  // the same honest answer without the data as the two above: none.
  if (reports === "open") lines = lines.filter((line) => (reportsOf?.get(line.lineId) ?? 0) > 0);
  // A restoration is not a rewrite: it puts a stripped stage direction back and changes no
  // words, so it does not belong in a list of lines someone rewrote by hand.
  if (overridden) {
    lines = lines.filter((line) => {
      const override = overrides.get(audioRelPath(line))?.text;
      return override !== undefined && !restoresOnlyNarration(override, line.text);
    });
  }

  // A file with no record counts as generated infinitely long ago, so it passes every
  // "before" and fails every "after". An unparseable bound is dropped rather than matching
  // nothing, for the same reason search-request.ts drops an unknown facet.
  const before = generatedBefore ? dayStart(generatedBefore) : null;
  if (before !== null) {
    // Through the end of the named day, which is what picking it off a calendar means.
    const until = before + DAY_MS;
    lines = lines.filter((line) => {
      const at = generatedAt?.get(audioRelPath(line));
      return at === undefined || at < until;
    });
  }

  const after = generatedAfter ? dayStart(generatedAfter) : null;
  if (after !== null) {
    lines = lines.filter((line) => {
      const at = generatedAt?.get(audioRelPath(line));
      return at !== undefined && at >= after;
    });
  }

  return [...lines].sort(order);
}

export function search(
  corpus: Corpus,
  store: Set<string>,
  { offset = 0, limit = PAGE_SIZE, ...filters }: SearchOptions = {},
  context: SearchContext = NO_CONTEXT,
): SearchResult {
  const all = matchingLines(corpus, store, filters, context);
  const keys = rowKeys(corpus);

  const start = Math.max(0, Math.floor(offset));
  const lines = all.slice(start, start + limit).map((line) => {
    const audioPath = audioRelPath(line);
    const override = context.overrides.get(audioPath)?.text ?? null;
    return {
      ...line,
      key: keys.get(line)!,
      hasAudio: store.has(audioPath),
      audioPath,
      reportsOpen: context.reports?.get(line.lineId) ?? 0,
      take: context.takes?.get(audioPath) ?? null,
      // From the context when it was asked for -- a filter on either needs the whole set.
      // The search route fills in the page otherwise; see there.
      stale: context.stale?.has(audioPath) ?? false,
      dirty: context.dirty?.has(audioPath) ?? false,
      override,
      voiceable: isVoiceable(line, override ?? line.text),
      narration: hasNarration(override ?? line.text),
      narrationRestored: override !== null && restoresOnlyNarration(override, line.text),
      ignored: context.ignores?.get(line.lineId)?.reason ?? null,
    };
  });

  return {
    lines,
    total: all.length,
    npcCount: new Set(all.map(npcKey)).size,
    offset: start,
    limit,
  };
}
